2025-01-10 13:16:10,153 - INFO - 作業開始
2025-01-10 13:16:10,154 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 13:16:10,192 - INFO - 【待注音漢字】總字數為: 143
2025-01-10 13:16:10,286 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, None, None, None, 0, -2146827284), None)
Traceback (most recent call last):
  File "a701_作業中活頁檔填入漢字.py", line 91, in main
    clear_han_ji_kap_piau_im(wb)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^
  File "c:\work\Piau-Im\p701_Clear_Cells.py", line 15, in clear_han_ji_kap_piau_im
    sheet.range(cells_range).clear_contents()     # 清除 C3:R{end_of_row} 範圍的內容
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2048, in clear_contents
    return self.impl.clear_contents()
           ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1213, in clear_contents
    self.xl.ClearContents()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject Range>", line 2, in ClearContents
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, None, None, None, 0, -2146827284), None)
2025-01-10 13:17:02,147 - INFO - 作業開始
2025-01-10 13:17:02,148 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 13:17:02,184 - INFO - 【待注音漢字】總字數為: 143
2025-01-10 13:17:02,368 - INFO - 儲存格清除完畢
2025-01-10 13:17:10,237 - INFO - 儲存格格式重設完畢
2025-01-10 13:17:26,865 - INFO - 填入待注音漢字完成
2025-01-10 13:17:26,908 - INFO - 開始標音作業 - 河洛話: 白話音
2025-01-10 13:17:46,412 - INFO - 標音作業完成 - 河洛話: 白話音
2025-01-10 13:17:46,761 - INFO - 檔案已成功儲存
2025-01-10 13:57:20,329 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 13:57:20,504 - INFO - 開始【漢字注音】工作表的清空、重置！
2025-01-10 13:57:26,854 - INFO - 【漢字注音】工作表的清空、重置失敗！
2025-01-10 13:57:26,854 - ERROR - 作業正常完成！
2025-01-10 13:59:14,756 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 13:59:14,892 - INFO - 開始【漢字注音】工作表的清空、重置！
2025-01-10 14:00:45,144 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 14:00:45,279 - INFO - 開始【漢字注音】工作表的清空、重置！
2025-01-10 14:01:02,787 - INFO - 完成【漢字注音】工作表的清空、重置！
2025-01-10 14:01:10,139 - INFO - 【漢字注音】工作表已清空、重置！
2025-01-10 14:01:35,427 - ERROR - 作業正常完成！
2025-01-10 14:25:19,037 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 14:25:19,128 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, None, None, None, 0, -2146827284), None)
Traceback (most recent call last):
  File "a700_重置漢字標音工作表.py", line 119, in main
    result_code = process(wb)
  File "a700_重置漢字標音工作表.py", line 63, in process
    sheet.range(cells_range).clear_contents()     # 清除 C3:R{end_of_row} 範圍的內容
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2048, in clear_contents
    return self.impl.clear_contents()
           ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1213, in clear_contents
    self.xl.ClearContents()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject Range>", line 2, in ClearContents
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, None, None, None, 0, -2146827284), None)
2025-01-10 14:25:19,195 - INFO - 釋放 Excel 資源，處理完成。
2025-01-10 14:25:43,418 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 14:25:43,548 - INFO - 開始【漢字注音】工作表的清空、重置！
2025-01-10 14:26:04,791 - INFO - 完成【漢字注音】工作表的清空、重置！
2025-01-10 14:26:04,869 - INFO - 【漢字注音】工作表已清空、重置！
2025-01-10 14:26:04,929 - INFO - 釋放 Excel 資源，處理完成。
2025-01-10 14:26:04,929 - INFO - 作業成功完成！
2025-01-10 14:28:10,604 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 14:28:10,749 - INFO - 開始【漢字注音】工作表的清空、重置！
2025-01-10 14:28:23,303 - INFO - 完成【漢字注音】工作表的清空、重置！
2025-01-10 14:28:23,365 - INFO - 【漢字注音】工作表已清空、重置！
2025-01-10 14:28:23,423 - INFO - 釋放 Excel 資源，處理完成。
2025-01-10 14:28:23,423 - INFO - 作業成功完成！
2025-01-10 14:32:13,418 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 14:32:13,563 - INFO - 開始【漢字注音】工作表的清空、重置！
2025-01-10 14:32:19,974 - INFO - 完成【漢字注音】工作表的清空、重置！
2025-01-10 14:32:20,042 - INFO - 釋放 Excel 資源，處理完成。
2025-01-10 14:32:20,042 - INFO - 作業成功完成！
2025-01-10 14:32:59,851 - INFO - 作業開始
2025-01-10 14:32:59,852 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 14:32:59,884 - WARNING - 【待注音漢字】儲存格為空
2025-01-10 14:32:59,884 - ERROR - 作業正常完成！
2025-01-10 14:34:03,005 - INFO - 作業開始
2025-01-10 14:34:03,006 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 14:34:03,039 - INFO - 【待注音漢字】總字數為: 143
2025-01-10 14:34:03,172 - INFO - 儲存格清除完畢
2025-01-10 14:34:10,047 - INFO - 儲存格格式重設完畢
2025-01-10 14:34:22,636 - INFO - 填入待注音漢字完成
2025-01-10 14:34:22,676 - INFO - 開始標音作業 - 河洛話: 白話音
2025-01-10 14:34:36,680 - INFO - 標音作業完成 - 河洛話: 白話音
2025-01-10 14:34:36,988 - INFO - 檔案已成功儲存
2025-01-10 14:34:36,989 - ERROR - 作業正常完成！
2025-01-10 16:11:19,417 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 16:11:19,491 - INFO - 開始【處理作業】...
2025-01-10 16:11:19,492 - ERROR - 執行過程中發生未知錯誤: cannot access local variable 'end_of_file' where it is not associated with a value
Traceback (most recent call last):
  File "a705_輸出己標音漢字.py", line 170, in main
    result_code = process(wb)
  File "a705_輸出己標音漢字.py", line 98, in process
    if end_of_file:
       ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'end_of_file' where it is not associated with a value
2025-01-10 16:11:19,562 - INFO - 釋放 Excel 資源，處理完成。
2025-01-10 16:15:27,758 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 16:15:27,846 - INFO - 開始【處理作業】...
2025-01-10 16:15:30,051 - ERROR - 執行過程中發生未知錯誤: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "a705_輸出己標音漢字.py", line 170, in main
    result_code = process(wb)
  File "a705_輸出己標音漢字.py", line 114, in process
    han_ji_text += cell_value
TypeError: can only concatenate str (not "NoneType") to str
2025-01-10 16:15:30,122 - INFO - 釋放 Excel 資源，處理完成。
2025-01-10 16:16:28,279 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 16:16:28,355 - INFO - 開始【處理作業】...
2025-01-10 16:19:25,587 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 16:19:25,699 - INFO - 開始【處理作業】...
2025-01-10 16:21:40,265 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 16:21:40,343 - INFO - 開始【處理作業】...
2025-01-10 16:22:58,939 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 16:22:59,025 - INFO - 開始【處理作業】...
2025-01-10 16:26:27,700 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 16:26:27,775 - INFO - 開始【處理作業】...
2025-01-10 16:27:25,352 - ERROR - 執行過程中發生未知錯誤: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "a705_輸出己標音漢字.py", line 173, in main
    result_code = process(wb)
  File "a705_輸出己標音漢字.py", line 115, in process
    han_ji_text += cell_value
TypeError: can only concatenate str (not "NoneType") to str
2025-01-10 16:27:25,430 - INFO - 釋放 Excel 資源，處理完成。
2025-01-10 16:30:48,776 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 16:31:36,491 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 16:31:36,565 - INFO - 開始【處理作業】...
2025-01-10 16:31:44,530 - INFO - 已成功將漢字輸出至檔案：tmp.txt
2025-01-10 16:31:44,537 - INFO - 完成【處理作業】...
2025-01-10 16:31:44,605 - INFO - 釋放 Excel 資源，處理完成。
2025-01-10 16:31:44,605 - INFO - 作業成功完成！
2025-01-10 23:20:04,459 - INFO - 作業開始
2025-01-10 23:20:04,460 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 23:20:16,227 - ERROR - 標音漢字轉換為 HTML 網頁檔案失敗！
2025-01-10 23:20:16,227 - ERROR - 處理作業失敗，過程中出錯！
2025-01-10 23:20:16,228 - INFO - 【漢字注音】工作表中已標音之漢字已輸出到網頁！
2025-01-10 23:26:32,515 - INFO - 作業開始
2025-01-10 23:26:32,517 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 23:26:44,341 - INFO - 儲存檔案至路徑：C:\work\Piau-Im\output7\【河洛白話注音-雅俗通】《尚有力量的每日祈禱文》.xlsx
2025-01-10 23:26:44,342 - INFO - 【漢字注音】工作表中已標音之漢字已輸出到網頁！
2025-01-10 23:46:54,794 - INFO - 作業開始
2025-01-10 23:46:54,795 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-10 23:47:06,583 - INFO - 儲存檔案至路徑：.\output7\【河洛白話注音-雅俗通】《尚有力量的每日祈禱文》.xlsx
2025-01-10 23:47:06,584 - INFO - 製作【漢字標音】網頁己完成！
2025-01-11 13:03:18,256 - INFO - 作業開始
2025-01-11 13:03:18,258 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 13:03:18,295 - INFO - 【待注音漢字】總字數為: 143
2025-01-11 13:03:18,428 - INFO - 儲存格內容清除完畢
2025-01-11 13:03:24,900 - INFO - 儲存格格式重設完畢
2025-01-11 13:03:35,169 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-11 13:03:35,212 - INFO - 開始【漢字標音作業】 - 河洛話: 白話音
2025-01-11 13:03:46,665 - INFO - 完成【漢字標音作業】 - 河洛話: 白話音
2025-01-11 13:03:46,915 - INFO - 己存檔至路徑：{file_path}
2025-01-11 13:03:46,915 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-11 13:06:28,889 - INFO - 作業開始
2025-01-11 13:06:28,890 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 13:06:28,925 - INFO - 【待注音漢字】總字數為: 143
2025-01-11 13:06:29,076 - INFO - 儲存格內容清除完畢
2025-01-11 13:06:35,615 - INFO - 儲存格格式重設完畢
2025-01-11 13:06:45,842 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-11 13:06:45,889 - INFO - 開始【漢字標音作業】 - 河洛話: 白話音
2025-01-11 13:06:57,253 - INFO - 完成【漢字標音作業】 - 河洛話: 白話音
2025-01-11 13:06:57,506 - INFO - 己存檔至路徑：{file_path}
2025-01-11 13:06:57,507 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-11 13:13:18,588 - INFO - 作業開始
2025-01-11 13:13:18,589 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 13:13:18,622 - INFO - 【待注音漢字】總字數為: 143
2025-01-11 13:13:18,777 - INFO - 儲存格內容清除完畢
2025-01-11 13:13:25,307 - INFO - 儲存格格式重設完畢
2025-01-11 13:13:35,580 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-11 13:13:35,620 - INFO - 開始【漢字標音作業】 - 河洛話: 白話音
2025-01-11 13:13:47,015 - INFO - 完成【漢字標音作業】 - 河洛話: 白話音
2025-01-11 13:13:47,263 - INFO - 己存檔至路徑：{file_path}
2025-01-11 13:13:47,263 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-11 13:15:01,951 - INFO - 作業開始
2025-01-11 13:15:01,952 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 13:15:01,984 - INFO - 【待注音漢字】總字數為: 143
2025-01-11 13:15:02,122 - INFO - 儲存格內容清除完畢
2025-01-11 13:15:08,685 - INFO - 儲存格格式重設完畢
2025-01-11 13:15:18,972 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-11 13:15:19,013 - INFO - 開始【漢字標音作業】 - 河洛話: 白話音
2025-01-11 13:15:31,071 - INFO - 完成【漢字標音作業】 - 河洛話: 白話音
2025-01-11 13:15:31,328 - INFO - 己存檔至路徑：{file_path}
2025-01-11 13:15:31,328 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-11 13:19:40,324 - INFO - 作業開始
2025-01-11 13:19:40,325 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 13:19:40,360 - INFO - 【待注音漢字】總字數為: 143
2025-01-11 13:19:40,499 - INFO - 儲存格內容清除完畢
2025-01-11 13:19:47,170 - INFO - 儲存格格式重設完畢
2025-01-11 13:19:57,678 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-11 13:19:57,721 - INFO - 開始【漢字標音作業】 - 河洛話: 白話音
2025-01-11 13:20:09,417 - INFO - 完成【漢字標音作業】 - 河洛話: 白話音
2025-01-11 13:20:09,669 - INFO - 己存檔至路徑：{file_path}
2025-01-11 13:20:09,669 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-11 14:33:24,971 - INFO - 作業開始
2025-01-11 14:33:24,972 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 14:33:25,009 - INFO - 【待注音漢字】總字數為: 143
2025-01-11 14:33:25,167 - INFO - 儲存格內容清除完畢
2025-01-11 14:33:31,791 - INFO - 儲存格格式重設完畢
2025-01-11 14:33:42,210 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-11 14:33:42,257 - INFO - 開始【漢字標音作業】 - 河洛話: 白話音
2025-01-11 14:36:37,582 - INFO - 作業開始
2025-01-11 14:36:37,583 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 14:36:37,617 - INFO - 【待注音漢字】總字數為: 143
2025-01-11 14:36:37,716 - INFO - 儲存格內容清除完畢
2025-01-11 14:36:44,319 - INFO - 儲存格格式重設完畢
2025-01-11 14:36:54,603 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-11 14:36:54,645 - INFO - 開始【漢字標音作業】 - 河洛話: 白話音
2025-01-11 14:37:06,155 - INFO - 完成【漢字標音作業】 - 河洛話: 白話音
2025-01-11 14:37:06,408 - INFO - 己存檔至路徑：{file_path}
2025-01-11 14:37:06,408 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-11 14:44:47,264 - INFO - 作業開始
2025-01-11 14:44:47,266 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 14:44:47,306 - INFO - 【待注音漢字】總字數為: 143
2025-01-11 14:44:47,463 - INFO - 儲存格內容清除完畢
2025-01-11 14:44:54,230 - INFO - 儲存格格式重設完畢
2025-01-11 14:45:05,056 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-11 14:45:05,122 - INFO - 開始【漢字標音作業】 - 河洛話: 白話音
2025-01-11 14:45:16,742 - INFO - 完成【漢字標音作業】 - 河洛話: 白話音
2025-01-11 14:45:17,014 - INFO - 己存檔至路徑：{file_path}
2025-01-11 14:45:17,015 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-11 14:47:19,203 - INFO - 作業開始
2025-01-11 14:47:19,204 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 14:47:19,237 - INFO - 【待注音漢字】總字數為: 143
2025-01-11 14:47:19,377 - INFO - 儲存格內容清除完畢
2025-01-11 14:47:25,841 - INFO - 儲存格格式重設完畢
2025-01-11 14:47:36,332 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-11 14:47:36,377 - INFO - 開始【漢字標音作業】 - 河洛話: 白話音
2025-01-11 14:47:47,923 - INFO - 完成【漢字標音作業】 - 河洛話: 白話音
2025-01-11 14:47:48,189 - INFO - 己存檔至路徑：{file_path}
2025-01-11 14:47:48,189 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-11 14:52:30,445 - INFO - 作業開始
2025-01-11 14:52:30,447 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 14:52:30,481 - INFO - 【待注音漢字】總字數為: 143
2025-01-11 14:52:30,620 - INFO - 儲存格內容清除完畢
2025-01-11 14:52:37,248 - INFO - 儲存格格式重設完畢
2025-01-11 14:52:47,606 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-11 14:52:47,651 - INFO - 開始【漢字標音作業】 - 河洛話: 白話音
2025-01-11 14:52:59,036 - INFO - 完成【漢字標音作業】 - 河洛話: 白話音
2025-01-11 14:52:59,295 - INFO - 己存檔至路徑：{file_path}
2025-01-11 14:52:59,295 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-11 15:14:14,843 - INFO - 作業開始
2025-01-11 15:14:14,844 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 15:14:26,941 - INFO - a700_重罝漢字標音工作表.py 程式已執行完畢！
2025-01-11 15:14:26,941 - INFO - 作業完成！
2025-01-11 15:21:35,584 - INFO - 作業開始
2025-01-11 15:21:35,585 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 15:21:47,811 - INFO - 己存檔至路徑：{file_path}
2025-01-11 15:21:47,811 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-11 15:21:47,811 - INFO - 作業完成！
2025-01-11 15:36:44,580 - INFO - 作業開始
2025-01-11 15:36:44,583 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 15:36:57,063 - INFO - 儲存檔案至路徑：.\output7\【河洛白話注音-雅俗通】《上有力量的每日祈禱文》.xlsx
2025-01-11 15:36:57,063 - INFO - 製作【漢字標音】網頁己完成！
2025-01-11 15:36:57,063 - INFO - 作業完成！
2025-01-11 16:13:20,687 - INFO - 作業開始
2025-01-11 16:13:20,688 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 16:13:21,031 - ERROR - 作業過程發生未知的異常錯誤: cannot access local variable 'EOF' where it is not associated with a value
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 148, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 66, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name="han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\work\Piau-Im\p702_Ca_Han_Ji_Thak_Im.py", line 210, in ca_han_ji_thak_im
    if msg == "【換行】" or EOF:
                            ^^^
UnboundLocalError: cannot access local variable 'EOF' where it is not associated with a value
2025-01-11 16:13:21,035 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-11 16:35:41,571 - INFO - 作業開始
2025-01-11 16:35:41,573 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 16:35:53,593 - INFO - 己存檔至路徑：{file_path}
2025-01-11 16:35:53,593 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-11 16:35:53,593 - INFO - 作業完成！
2025-01-11 16:36:38,828 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 16:36:38,916 - INFO - 開始【處理作業】...
2025-01-11 16:36:41,362 - INFO - 已成功將漢字輸出至檔案：tmp.txt
2025-01-11 16:36:41,370 - INFO - 完成【處理作業】...
2025-01-11 16:36:41,442 - INFO - 釋放 Excel 資源，處理完成。
2025-01-11 16:36:41,442 - INFO - 作業成功完成！
2025-01-11 16:38:02,211 - INFO - 作業開始
2025-01-11 16:38:02,212 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 16:38:14,597 - INFO - 儲存檔案至路徑：.\output7\【河洛白話注音-雅俗通】《上有力量的每日祈禱文》.xlsx
2025-01-11 16:38:14,598 - INFO - 製作【漢字標音】網頁己完成！
2025-01-11 16:38:14,598 - INFO - 作業完成！
2025-01-11 16:55:10,202 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 16:55:10,280 - INFO - 開始【處理作業】...
2025-01-11 16:55:12,672 - INFO - 已成功將漢字輸出至檔案：tmp.txt
2025-01-11 16:55:12,679 - INFO - 完成【處理作業】...
2025-01-11 16:55:12,827 - INFO - 釋放 Excel 資源，處理完成。
2025-01-11 16:55:12,827 - INFO - 作業成功完成！
2025-01-11 16:57:34,451 - INFO - 作業開始
2025-01-11 16:57:34,452 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 16:57:34,486 - INFO - 【待注音漢字】總字數為: 143
2025-01-11 16:57:34,636 - INFO - 儲存格內容清除完畢
2025-01-11 16:57:49,753 - INFO - 儲存格格式重設完畢
2025-01-11 16:58:21,388 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-11 16:58:21,494 - INFO - 開始【漢字標音作業】 - 河洛話: 白話音
2025-01-11 16:58:33,824 - INFO - 完成【漢字標音作業】 - 河洛話: 白話音
2025-01-11 16:58:34,075 - INFO - 儲存檔案至路徑：.\output7\【河洛白話注音-雅俗通】《上有力量的每日祈禱文》.xlsx
2025-01-11 16:58:34,075 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-11 17:01:43,792 - INFO - 作業開始
2025-01-11 17:01:43,793 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 17:05:01,118 - INFO - 作業開始
2025-01-11 17:05:01,119 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 17:11:43,898 - INFO - 作業開始
2025-01-11 17:11:43,899 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 17:15:12,833 - INFO - 己存檔至路徑：{file_path}
2025-01-11 17:15:12,833 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-11 17:15:12,833 - INFO - 作業完成！
2025-01-11 17:25:51,824 - INFO - 作業開始
2025-01-11 17:25:51,825 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 17:26:13,909 - ERROR - 作業過程發生未知的異常錯誤: ''
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 148, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 66, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name="han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\work\Piau-Im\p702_Ca_Han_Ji_Thak_Im.py", line 157, in ca_han_ji_thak_im
    han_ji_piau_im = tng_uann_han_ji_piau_im(
        piau_im,
    ...<3 lines>...
        tiau
    )
  File "c:\work\Piau-Im\mod_標音.py", line 150, in tng_uann_han_ji_piau_im
    return piau_im.NST_piau_im(siann_bu, un_bu, tiau_ho)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_標音.py", line 739, in NST_piau_im
    siann = self.Siann_Bu_Dict[siann_bu][piau_im_huat]
            ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: ''
2025-01-11 17:26:13,914 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-11 17:26:20,261 - INFO - 作業開始
2025-01-11 17:26:20,262 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 17:26:24,898 - ERROR - 作業過程發生未知的異常錯誤: ''
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 148, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 66, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name="han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\work\Piau-Im\p702_Ca_Han_Ji_Thak_Im.py", line 157, in ca_han_ji_thak_im
    han_ji_piau_im = tng_uann_han_ji_piau_im(
        piau_im,
    ...<3 lines>...
        tiau
    )
  File "c:\work\Piau-Im\mod_標音.py", line 150, in tng_uann_han_ji_piau_im
    return piau_im.NST_piau_im(siann_bu, un_bu, tiau_ho)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_標音.py", line 739, in NST_piau_im
    siann = self.Siann_Bu_Dict[siann_bu][piau_im_huat]
            ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: ''
2025-01-11 17:26:24,902 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-11 17:27:48,015 - INFO - 作業開始
2025-01-11 17:27:48,016 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 17:27:54,560 - ERROR - 作業過程發生未知的異常錯誤: ''
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 148, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 66, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name="han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\work\Piau-Im\p702_Ca_Han_Ji_Thak_Im.py", line 157, in ca_han_ji_thak_im
    han_ji_piau_im = tng_uann_han_ji_piau_im(
        piau_im,
    ...<3 lines>...
        tiau
    )
  File "c:\work\Piau-Im\mod_標音.py", line 150, in tng_uann_han_ji_piau_im
    return piau_im.NST_piau_im(siann_bu, un_bu, tiau_ho)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_標音.py", line 739, in NST_piau_im
    siann = self.Siann_Bu_Dict[siann_bu][piau_im_huat]
            ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: ''
2025-01-11 17:27:54,565 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-11 17:29:09,766 - INFO - 作業開始
2025-01-11 17:29:09,768 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 17:29:11,248 - ERROR - 作業過程發生未知的異常錯誤: ''
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 148, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 66, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name="han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\work\Piau-Im\p702_Ca_Han_Ji_Thak_Im.py", line 157, in ca_han_ji_thak_im
    han_ji_piau_im = tng_uann_han_ji_piau_im(
        piau_im,
    ...<3 lines>...
        tiau
    )
  File "c:\work\Piau-Im\mod_標音.py", line 150, in tng_uann_han_ji_piau_im
    return piau_im.NST_piau_im(siann_bu, un_bu, tiau_ho)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_標音.py", line 739, in NST_piau_im
    siann = self.Siann_Bu_Dict[siann_bu][piau_im_huat]
            ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: ''
2025-01-11 17:29:11,251 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-11 17:30:21,074 - INFO - 作業開始
2025-01-11 17:30:21,075 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 17:31:23,609 - ERROR - 作業過程發生未知的異常錯誤: ''
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 148, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 66, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name="han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\work\Piau-Im\p702_Ca_Han_Ji_Thak_Im.py", line 157, in ca_han_ji_thak_im
    han_ji_piau_im = tng_uann_han_ji_piau_im(
        piau_im,
    ...<3 lines>...
        tiau
    )
  File "c:\work\Piau-Im\mod_標音.py", line 150, in tng_uann_han_ji_piau_im
    return piau_im.NST_piau_im(siann_bu, un_bu, tiau_ho)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_標音.py", line 739, in NST_piau_im
    siann = self.Siann_Bu_Dict[siann_bu][piau_im_huat]
            ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: ''
2025-01-11 17:31:23,614 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-11 17:31:30,937 - INFO - 作業開始
2025-01-11 17:31:30,938 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 17:32:30,952 - ERROR - 作業過程發生未知的異常錯誤: ''
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 148, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 66, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name="han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\work\Piau-Im\p702_Ca_Han_Ji_Thak_Im.py", line 157, in ca_han_ji_thak_im
    han_ji_piau_im = tng_uann_han_ji_piau_im(
        piau_im,
    ...<3 lines>...
        tiau
    )
  File "c:\work\Piau-Im\mod_標音.py", line 150, in tng_uann_han_ji_piau_im
    return piau_im.NST_piau_im(siann_bu, un_bu, tiau_ho)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_標音.py", line 739, in NST_piau_im
    siann = self.Siann_Bu_Dict[siann_bu][piau_im_huat]
            ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: ''
2025-01-11 17:32:30,959 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-11 17:32:39,922 - INFO - 作業開始
2025-01-11 17:32:39,923 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 17:38:51,593 - INFO - 作業開始
2025-01-11 17:38:51,594 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 17:42:00,760 - INFO - 作業開始
2025-01-11 17:42:00,761 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 17:43:16,896 - INFO - 己存檔至路徑：{file_path}
2025-01-11 17:43:16,896 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-11 17:43:16,896 - INFO - 作業完成！
2025-01-11 19:31:47,222 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 19:31:47,319 - INFO - 開始【處理作業】...
2025-01-11 19:31:49,813 - INFO - 已成功將漢字輸出至檔案：tmp.txt
2025-01-11 19:31:49,820 - INFO - 完成【處理作業】...
2025-01-11 19:31:49,893 - INFO - 釋放 Excel 資源，處理完成。
2025-01-11 19:31:49,894 - INFO - 作業成功完成！
2025-01-11 19:36:17,454 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 19:36:17,550 - INFO - 開始【處理作業】...
2025-01-11 19:36:20,141 - INFO - 已更新【待注音漢字】儲存格！
2025-01-11 19:36:20,141 - INFO - 完成【處理作業】...
2025-01-11 19:36:20,210 - INFO - 釋放 Excel 資源，處理完成。
2025-01-11 19:36:20,210 - INFO - 作業成功完成！
2025-01-11 19:36:31,909 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 19:36:31,989 - INFO - 開始【處理作業】...
2025-01-11 19:36:53,844 - INFO - 已更新【待注音漢字】儲存格！
2025-01-11 19:37:24,488 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 19:37:24,569 - INFO - 開始【處理作業】...
2025-01-11 19:37:42,052 - INFO - 已更新【待注音漢字】儲存格！
2025-01-11 19:37:43,444 - INFO - 完成【處理作業】...
2025-01-11 19:41:52,403 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 19:41:52,495 - INFO - 開始【處理作業】...
2025-01-11 19:41:55,052 - INFO - 已更新【待注音漢字】儲存格！
2025-01-11 19:42:20,005 - INFO - 【待注音漢字】總字數為: 143
2025-01-11 19:42:20,113 - INFO - 儲存格內容清除完畢
2025-01-11 19:42:26,769 - INFO - 儲存格格式重設完畢
2025-01-11 19:42:37,466 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-11 19:42:37,511 - INFO - 開始【漢字標音作業】 - 河洛話: 白話音
2025-01-11 19:43:00,576 - INFO - 完成【漢字標音作業】 - 河洛話: 白話音
2025-01-11 19:43:00,827 - INFO - 儲存檔案至路徑：.\output7\【河洛白話注音-雅俗通】《上有力量的每日祈禱文》.xlsx
2025-01-11 19:45:29,635 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 19:45:29,731 - INFO - 開始【處理作業】...
2025-01-11 19:45:32,192 - INFO - 已更新【待注音漢字】儲存格！
2025-01-11 19:45:32,210 - INFO - 【待注音漢字】總字數為: 143
2025-01-11 19:45:32,317 - INFO - 儲存格內容清除完畢
2025-01-11 19:45:40,996 - INFO - 儲存格格式重設完畢
2025-01-11 19:45:52,992 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-11 19:45:53,032 - INFO - 開始【漢字標音作業】 - 河洛話: 白話音
2025-01-11 19:46:04,881 - INFO - 完成【漢字標音作業】 - 河洛話: 白話音
2025-01-11 19:46:05,122 - INFO - 儲存檔案至路徑：.\output7\【河洛白話注音-雅俗通】《上有力量的每日祈禱文》.xlsx
2025-01-11 19:46:05,122 - INFO - 已更新【漢字注音】工作表中的【台語音標】與【漢字標音】儲存格！
2025-01-11 19:46:10,896 - INFO - 完成【處理作業】...
2025-01-11 19:46:10,972 - INFO - 釋放 Excel 資源，處理完成。
2025-01-11 19:46:10,972 - INFO - 作業成功完成！
2025-01-11 19:48:14,344 - INFO - 作業開始
2025-01-11 19:48:14,345 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 19:48:26,754 - INFO - 己存檔至路徑：{file_path}
2025-01-11 19:48:26,754 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-11 19:48:26,754 - INFO - 作業完成！
2025-01-11 19:55:39,279 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 19:55:39,430 - INFO - 開始【處理作業】...
2025-01-11 19:55:41,973 - INFO - 已更新【待注音漢字】儲存格！
2025-01-11 19:55:41,991 - INFO - 【待注音漢字】總字數為: 143
2025-01-11 19:55:42,093 - INFO - 儲存格內容清除完畢
2025-01-11 19:55:48,706 - INFO - 儲存格格式重設完畢
2025-01-11 19:55:59,348 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-11 19:56:06,913 - ERROR - 執行過程中發生未知錯誤: 'Book' object has no attribute 'sheet'
Traceback (most recent call last):
  File "a705_依漢字注音工作表內容更新待注音漢字.py", line 192, in main
    result_code = process(wb)
  File "a705_依漢字注音工作表內容更新待注音漢字.py", line 152, in process
    fill_hanji_in_cells(wb)
    ~~~~~~~~~~~~~~~~~~~^^^^
  File "c:\work\Piau-Im\a701_作業中活頁檔填入漢字.py", line 89, in process
    ue_im_lui_piat = wb.sheet['env'].names['語音類型'].refers_to_range.value
                     ^^^^^^^^
AttributeError: 'Book' object has no attribute 'sheet'. Did you mean: 'sheets'?
2025-01-11 19:56:06,989 - INFO - 釋放 Excel 資源，處理完成。
2025-01-11 19:57:41,757 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 19:57:41,844 - INFO - 開始【處理作業】...
2025-01-11 19:57:44,319 - INFO - 已更新【待注音漢字】儲存格！
2025-01-11 19:57:44,337 - INFO - 【待注音漢字】總字數為: 143
2025-01-11 19:57:44,442 - INFO - 儲存格內容清除完畢
2025-01-11 19:57:50,928 - INFO - 儲存格格式重設完畢
2025-01-11 19:58:01,893 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-11 19:58:45,069 - INFO - 開始【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-11 19:58:57,356 - INFO - 完成【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-11 19:58:57,600 - INFO - 儲存檔案至路徑：.\output7\【河洛白話注音-雅俗通】《上有力量的每日祈禱文》.xlsx
2025-01-11 19:58:57,600 - INFO - 已更新【漢字注音】工作表中的【台語音標】與【漢字標音】儲存格！
2025-01-11 19:58:57,600 - INFO - 完成【處理作業】...
2025-01-11 19:58:57,666 - INFO - 釋放 Excel 資源，處理完成。
2025-01-11 19:58:57,666 - INFO - 作業成功完成！
2025-01-11 20:04:44,630 - INFO - 作業開始
2025-01-11 20:04:44,631 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-11 20:05:08,129 - INFO - 己存檔至路徑：{file_path}
2025-01-11 20:05:08,130 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-11 20:05:08,130 - INFO - 作業完成！
2025-01-12 11:57:33,534 - INFO - 作業開始
2025-01-12 11:57:33,535 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 11:59:32,960 - INFO - 作業開始
2025-01-12 11:59:32,961 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 12:02:34,943 - INFO - 作業開始
2025-01-12 12:02:34,944 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 12:03:08,497 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 12:06:08,812 - INFO - 作業開始
2025-01-12 12:06:08,813 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 12:06:14,577 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 12:08:32,862 - INFO - 作業開始
2025-01-12 12:08:32,863 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 12:08:37,850 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 12:13:43,161 - INFO - 作業開始
2025-01-12 12:13:43,162 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 12:13:43,383 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 12:18:14,324 - INFO - 作業開始
2025-01-12 12:18:14,325 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 12:18:14,881 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 13:49:36,574 - INFO - 作業開始
2025-01-12 13:49:36,575 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 13:49:36,653 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 13:52:18,006 - INFO - 作業開始
2025-01-12 13:52:18,007 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 13:52:18,084 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 14:24:49,344 - INFO - 作業開始
2025-01-12 14:24:49,346 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 14:31:15,445 - INFO - 作業開始
2025-01-12 14:31:15,446 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 14:34:05,627 - INFO - 作業開始
2025-01-12 14:34:05,628 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 14:35:07,093 - INFO - 作業開始
2025-01-12 14:35:07,094 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 14:56:38,791 - INFO - 作業開始
2025-01-12 14:56:38,792 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 14:56:59,049 - ERROR - 作業過程發生未知的異常錯誤: list index out of range
Traceback (most recent call last):
  File "mod_excel.py", line 302, in main
    result_code = process(wb)
  File "mod_excel.py", line 262, in process
    return_code = ut_maintain_han_ji_koo(wb=wb)
  File "mod_excel.py", line 165, in ut_maintain_han_ji_koo
    maintain_han_ji_koo(wb, "漢字庫", "說", "sue3")
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mod_excel.py", line 87, in maintain_han_ji_koo
    if row[0] == han_ji and row[1] == tai_gi:
                            ~~~^^^
IndexError: list index out of range
2025-01-12 14:56:59,052 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 14:58:18,242 - INFO - 作業開始
2025-01-12 14:58:18,243 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 14:58:39,487 - INFO - 作業開始
2025-01-12 14:58:39,488 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 15:03:40,262 - INFO - 作業開始
2025-01-12 15:03:40,263 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 15:03:49,283 - ERROR - 作業過程發生未知的異常錯誤: 'float' object is not iterable
Traceback (most recent call last):
  File "mod_excel.py", line 302, in main
    result_code = process(wb)
  File "mod_excel.py", line 262, in process
    return_code = ut_maintain_han_ji_koo(wb=wb)
  File "mod_excel.py", line 165, in ut_maintain_han_ji_koo
    maintain_han_ji_koo(wb, "漢字庫", "說", "sue3")
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mod_excel.py", line 82, in maintain_han_ji_koo
    records = [[r if r is not None else "" for r in row] for row in data]
                                                    ^^^
TypeError: 'float' object is not iterable
2025-01-12 15:03:49,287 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 15:04:58,559 - INFO - 作業開始
2025-01-12 15:04:58,560 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 15:05:40,895 - ERROR - 作業過程發生未知的異常錯誤: 'float' object is not iterable
Traceback (most recent call last):
  File "mod_excel.py", line 302, in main
    result_code = process(wb)
  File "mod_excel.py", line 262, in process
    return_code = ut_maintain_han_ji_koo(wb=wb)
  File "mod_excel.py", line 165, in ut_maintain_han_ji_koo
    maintain_han_ji_koo(wb, "漢字庫", "說", "sue3")
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mod_excel.py", line 82, in maintain_han_ji_koo
    records = [[r if r is not None else "" for r in row] for row in data]
                                                    ^^^
TypeError: 'float' object is not iterable
2025-01-12 15:05:40,899 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 15:08:26,631 - INFO - 作業開始
2025-01-12 15:08:26,632 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 15:12:56,765 - INFO - 作業開始
2025-01-12 15:12:56,766 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 15:13:16,585 - INFO - 作業開始
2025-01-12 15:13:16,586 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 15:21:36,331 - INFO - 作業開始
2025-01-12 15:21:36,332 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 15:21:36,725 - ERROR - 作業過程發生未知的異常錯誤: cannot access local variable 'found' where it is not associated with a value
Traceback (most recent call last):
  File "mod_excel.py", line 320, in main
    result_code = process(wb)
  File "mod_excel.py", line 280, in process
    return_code = ut_maintain_han_ji_koo(wb=wb)
  File "mod_excel.py", line 181, in ut_maintain_han_ji_koo
    maintain_han_ji_koo(wb, "漢字庫", "說", "sue3")
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mod_excel.py", line 112, in maintain_han_ji_koo
    if not found:
           ^^^^^
UnboundLocalError: cannot access local variable 'found' where it is not associated with a value
2025-01-12 15:21:36,728 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 15:26:53,598 - INFO - 作業開始
2025-01-12 15:26:53,599 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 15:26:53,614 - ERROR - 作業過程發生未知的異常錯誤: name 'maintain_han_ji_koo' is not defined
Traceback (most recent call last):
  File "mod_excel.py", line 303, in main
    result_code = process(wb)
  File "mod_excel.py", line 250, in process
    return_code = ut_maintain_han_ji_koo(wb=wb)
  File "mod_excel.py", line 163, in ut_maintain_han_ji_koo
    maintain_han_ji_koo(wb, "漢字庫", "說", "sue3")
    ^^^^^^^^^^^^^^^^^^^
NameError: name 'maintain_han_ji_koo' is not defined. Did you mean: 'maintain_han_ji_ku'?
2025-01-12 15:26:53,619 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 15:27:39,555 - INFO - 作業開始
2025-01-12 15:27:39,556 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 15:28:01,946 - ERROR - 作業過程發生未知的異常錯誤: 'float' object is not iterable
Traceback (most recent call last):
  File "mod_excel.py", line 303, in main
    result_code = process(wb)
  File "mod_excel.py", line 250, in process
    return_code = ut_maintain_han_ji_koo(wb=wb)
  File "mod_excel.py", line 165, in ut_maintain_han_ji_koo
    maintain_han_ji_koo(wb, "漢字庫", "說", "sue3")
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mod_excel.py", line 82, in maintain_han_ji_koo
    records = [[r if r is not None else "" for r in row] for row in data]
                                                    ^^^
TypeError: 'float' object is not iterable
2025-01-12 15:28:01,949 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 15:35:02,772 - INFO - 作業開始
2025-01-12 15:35:02,773 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 15:36:15,572 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 15:39:21,091 - INFO - 作業開始
2025-01-12 15:39:21,092 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 15:39:22,928 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 15:40:31,445 - INFO - 作業開始
2025-01-12 15:40:31,446 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 15:40:33,280 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 15:41:29,510 - INFO - 作業開始
2025-01-12 15:41:29,511 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 15:41:31,484 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 15:41:47,290 - INFO - 作業開始
2025-01-12 15:41:47,291 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 15:41:49,473 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 16:06:15,888 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 16:06:16,046 - INFO - 開始【處理作業】...
2025-01-12 16:07:10,084 - INFO - 已更新【待注音漢字】儲存格！
2025-01-12 16:07:10,104 - INFO - 【待注音漢字】總字數為: 143
2025-01-12 16:07:10,295 - INFO - 儲存格內容清除完畢
2025-01-12 16:07:19,469 - INFO - 儲存格格式重設完畢
2025-01-12 16:07:38,674 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-12 16:07:38,714 - INFO - 開始【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-12 16:07:58,671 - INFO - 完成【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-12 16:07:58,864 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', '您不能使用這個檔名存檔，因為已經有同樣檔名的檔案或增益集被開啟了。請選用其他的檔名，或將那個同名的檔案或增益集關閉。', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a000.py", line 201, in main
    result_code = process(wb)
  File "a000.py", line 161, in process
    fill_hanji_in_cells(wb)
    ~~~~~~~~~~~~~~~~~~~^^^^
  File "c:\work\Piau-Im\a701_作業中活頁檔填入漢字.py", line 112, in process
    file_path = save_as_new_file(wb=wb)
  File "c:\work\Piau-Im\mod_file_access.py", line 41, in save_as_new_file
    wb.save(new_file_path)
    ~~~~~~~^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 1169, in save
    self.impl.save(path, password=password)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 894, in save
    self.xl.SaveAs(
    ~~~~~~~~~~~~~~^
        os.path.realpath(path), FileFormat=file_format, Password=password
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 4, in SaveAs
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', '您不能使用這個檔名存檔，因為已經有同樣檔名的檔案或增益集被開啟了。請選用其他的檔名，或將那個同名的檔案或增益集關閉。', 'xlmain11.chm', 0, -2146827284), None)
2025-01-12 16:07:59,031 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 16:10:22,018 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 16:10:22,177 - INFO - 開始【處理作業】...
2025-01-12 16:10:26,094 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a000.py", line 185, in main
    result_code = process(wb)
  File "a000.py", line 96, in process
    sheet.range((row, 1)).select()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2815, in select
    self.impl.select()
    ~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1500, in select
    return self.xl.Select()
           ~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in Select
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
2025-01-12 16:10:26,284 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 16:12:09,580 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 16:12:09,748 - INFO - 開始【處理作業】...
2025-01-12 16:16:15,085 - INFO - 完成【處理作業】...
2025-01-12 16:16:15,262 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 16:16:15,262 - INFO - 作業成功完成！
2025-01-12 16:17:06,275 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 16:17:06,437 - INFO - 開始【處理作業】...
2025-01-12 16:17:59,961 - INFO - 完成【處理作業】...
2025-01-12 16:18:00,159 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 16:18:00,159 - INFO - 作業成功完成！
2025-01-12 16:19:28,968 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 16:19:29,081 - INFO - 開始【處理作業】...
2025-01-12 16:19:33,352 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a000.py", line 185, in main
    result_code = process(wb)
  File "a000.py", line 96, in process
    sheet.range((row, 1)).select()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2815, in select
    self.impl.select()
    ~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1500, in select
    return self.xl.Select()
           ~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in Select
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
2025-01-12 16:19:33,539 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 16:21:07,918 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 16:21:08,030 - INFO - 開始【處理作業】...
2025-01-12 16:21:12,310 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a000.py", line 185, in main
    result_code = process(wb)
  File "a000.py", line 96, in process
    sheet.range((row, 1)).select()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2815, in select
    self.impl.select()
    ~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1500, in select
    return self.xl.Select()
           ~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in Select
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
2025-01-12 16:21:12,513 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 16:23:07,250 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 16:23:07,361 - INFO - 開始【處理作業】...
2025-01-12 16:23:11,547 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a000.py", line 185, in main
    result_code = process(wb)
  File "a000.py", line 96, in process
    sheet.range((row, 1)).select()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2815, in select
    self.impl.select()
    ~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1500, in select
    return self.xl.Select()
           ~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in Select
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
2025-01-12 16:23:11,743 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 16:23:46,644 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 16:23:46,758 - INFO - 開始【處理作業】...
2025-01-12 16:24:29,700 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a000.py", line 185, in main
    result_code = process(wb)
  File "a000.py", line 96, in process
    sheet.range((row, 1)).select()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2815, in select
    self.impl.select()
    ~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1500, in select
    return self.xl.Select()
           ~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in Select
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
2025-01-12 16:24:29,900 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 16:40:18,453 - INFO - 作業開始
2025-01-12 16:40:18,454 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 16:40:54,956 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 16:41:40,921 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 16:41:41,092 - INFO - 開始【處理作業】...
2025-01-12 16:41:41,152 - ERROR - 執行過程中發生未知錯誤: maintain_han_ji_koo() got an unexpected keyword argument 'wb'
Traceback (most recent call last):
  File "a000.py", line 185, in main
    result_code = process(wb)
  File "a000.py", line 120, in process
    maintain_han_ji_koo(wb=wb, sheet_name="漢字庫",
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        han_ji=han_ji, tai_gi=tai_gi)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: maintain_han_ji_koo() got an unexpected keyword argument 'wb'
2025-01-12 16:41:41,343 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 16:45:22,782 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 16:45:23,338 - INFO - 開始【處理作業】...
2025-01-12 16:48:47,154 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 16:48:47,609 - INFO - 開始【處理作業】...
2025-01-12 16:49:34,805 - INFO - 完成【處理作業】...
2025-01-12 16:49:34,980 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 16:49:34,980 - INFO - 作業成功完成！
2025-01-12 17:09:46,442 - INFO - 作業開始
2025-01-12 17:09:46,444 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 17:10:49,689 - ERROR - 作業過程發生未知的異常錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', '您不能使用這個檔名存檔，因為已經有同樣檔名的檔案或增益集被開啟了。請選用其他的檔名，或將那個同名的檔案或增益集關閉。', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 148, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 107, in process
    save_as_new_file(wb=wb)
    ~~~~~~~~~~~~~~~~^^^^^^^
  File "c:\work\Piau-Im\mod_file_access.py", line 41, in save_as_new_file
    wb.save(new_file_path)
    ~~~~~~~^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 1169, in save
    self.impl.save(path, password=password)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 894, in save
    self.xl.SaveAs(
    ~~~~~~~~~~~~~~^
        os.path.realpath(path), FileFormat=file_format, Password=password
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 4, in SaveAs
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', '您不能使用這個檔名存檔，因為已經有同樣檔名的檔案或增益集被開啟了。請選用其他的檔名，或將那個同名的檔案或增益集關閉。', 'xlmain11.chm', 0, -2146827284), None)
2025-01-12 17:10:49,694 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-12 18:45:33,637 - INFO - 作業開始
2025-01-12 18:45:33,638 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 18:45:47,773 - ERROR - 作業過程發生未知的異常錯誤: (-2147352567, '發生例外狀況。', (0, None, None, None, 0, -2146827284), None)
Traceback (most recent call last):
  File "mod_excel_access.py", line 358, in main
    result_code = process(wb)
  File "mod_excel_access.py", line 305, in process
    return_code = ut_maintain_han_ji_koo(wb=wb)
  File "mod_excel_access.py", line 209, in ut_maintain_han_ji_koo
    maintain_han_ji_koo(sheet, "說", "sue3")
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "mod_excel_access.py", line 114, in maintain_han_ji_koo
    sheet.range("A2").expand("table").clear_contents()  # 清空舊資料
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2048, in clear_contents
    return self.impl.clear_contents()
           ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1213, in clear_contents
    self.xl.ClearContents()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject Range>", line 2, in ClearContents
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, None, None, None, 0, -2146827284), None)
2025-01-12 18:45:47,779 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 18:46:20,612 - INFO - 作業開始
2025-01-12 18:46:20,613 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 18:46:20,873 - ERROR - 作業過程發生未知的異常錯誤: (-2147352567, '發生例外狀況。', (0, None, None, None, 0, -2146827284), None)
Traceback (most recent call last):
  File "mod_excel_access.py", line 358, in main
    result_code = process(wb)
  File "mod_excel_access.py", line 305, in process
    return_code = ut_maintain_han_ji_koo(wb=wb)
  File "mod_excel_access.py", line 209, in ut_maintain_han_ji_koo
    maintain_han_ji_koo(sheet, "說", "sue3")
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "mod_excel_access.py", line 114, in maintain_han_ji_koo
    sheet.range("A2").expand("table").clear_contents()  # 清空舊資料
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2048, in clear_contents
    return self.impl.clear_contents()
           ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1213, in clear_contents
    self.xl.ClearContents()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject Range>", line 2, in ClearContents
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, None, None, None, 0, -2146827284), None)
2025-01-12 18:46:20,878 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 18:47:03,964 - INFO - 作業開始
2025-01-12 18:47:03,965 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 18:54:16,002 - INFO - 作業開始
2025-01-12 18:54:16,004 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 18:55:15,338 - INFO - 作業開始
2025-01-12 18:55:15,339 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 18:55:44,102 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 18:56:52,085 - INFO - 作業開始
2025-01-12 18:56:52,086 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 18:56:54,137 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 18:58:34,600 - INFO - 作業開始
2025-01-12 18:58:34,601 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 18:59:36,021 - ERROR - 作業過程發生未知的異常錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', '您不能使用這個檔名存檔，因為已經有同樣檔名的檔案或增益集被開啟了。請選用其他的檔名，或將那個同名的檔案或增益集關閉。', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 148, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 107, in process
    save_as_new_file(wb=wb)
    ~~~~~~~~~~~~~~~~^^^^^^^
  File "c:\work\Piau-Im\mod_file_access.py", line 41, in save_as_new_file
    wb.save(new_file_path)
    ~~~~~~~^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 1169, in save
    self.impl.save(path, password=password)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 894, in save
    self.xl.SaveAs(
    ~~~~~~~~~~~~~~^
        os.path.realpath(path), FileFormat=file_format, Password=password
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 4, in SaveAs
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', '您不能使用這個檔名存檔，因為已經有同樣檔名的檔案或增益集被開啟了。請選用其他的檔名，或將那個同名的檔案或增益集關閉。', 'xlmain11.chm', 0, -2146827284), None)
2025-01-12 18:59:36,026 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-12 19:04:31,426 - INFO - 作業開始
2025-01-12 19:04:31,427 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 19:04:33,678 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 19:05:13,674 - INFO - 作業開始
2025-01-12 19:05:13,675 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 19:06:14,419 - ERROR - 作業過程發生未知的異常錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', '您不能使用這個檔名存檔，因為已經有同樣檔名的檔案或增益集被開啟了。請選用其他的檔名，或將那個同名的檔案或增益集關閉。', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 148, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 107, in process
    save_as_new_file(wb=wb)
    ~~~~~~~~~~~~~~~~^^^^^^^
  File "c:\work\Piau-Im\mod_file_access.py", line 41, in save_as_new_file
    wb.save(new_file_path)
    ~~~~~~~^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 1169, in save
    self.impl.save(path, password=password)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 894, in save
    self.xl.SaveAs(
    ~~~~~~~~~~~~~~^
        os.path.realpath(path), FileFormat=file_format, Password=password
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 4, in SaveAs
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', '您不能使用這個檔名存檔，因為已經有同樣檔名的檔案或增益集被開啟了。請選用其他的檔名，或將那個同名的檔案或增益集關閉。', 'xlmain11.chm', 0, -2146827284), None)
2025-01-12 19:06:14,424 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-12 19:07:39,787 - INFO - 作業開始
2025-01-12 19:07:39,789 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 19:07:41,920 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-12 19:08:13,849 - INFO - 作業開始
2025-01-12 19:08:13,850 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 19:09:13,703 - ERROR - 作業過程發生未知的異常錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', '您不能使用這個檔名存檔，因為已經有同樣檔名的檔案或增益集被開啟了。請選用其他的檔名，或將那個同名的檔案或增益集關閉。', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 148, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 107, in process
    save_as_new_file(wb=wb)
    ~~~~~~~~~~~~~~~~^^^^^^^
  File "c:\work\Piau-Im\mod_file_access.py", line 41, in save_as_new_file
    wb.save(new_file_path)
    ~~~~~~~^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 1169, in save
    self.impl.save(path, password=password)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 894, in save
    self.xl.SaveAs(
    ~~~~~~~~~~~~~~^
        os.path.realpath(path), FileFormat=file_format, Password=password
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 4, in SaveAs
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', '您不能使用這個檔名存檔，因為已經有同樣檔名的檔案或增益集被開啟了。請選用其他的檔名，或將那個同名的檔案或增益集關閉。', 'xlmain11.chm', 0, -2146827284), None)
2025-01-12 19:09:13,708 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-12 19:11:37,107 - INFO - 作業開始
2025-01-12 19:11:37,109 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 19:11:55,966 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-12 19:12:24,637 - INFO - 作業開始
2025-01-12 19:12:24,638 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 19:15:25,045 - INFO - 作業開始
2025-01-12 19:15:25,046 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 19:18:12,505 - INFO - 作業開始
2025-01-12 19:18:12,506 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 19:19:33,277 - INFO - 己存檔至路徑：{file_path}
2025-01-12 19:19:33,278 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-12 19:19:33,278 - INFO - 作業完成！
2025-01-12 20:38:12,329 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 20:38:25,591 - INFO - 完成【作業程序2】...
2025-01-12 20:38:25,591 - INFO - 完成【處理作業】...
2025-01-12 20:38:25,689 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 20:38:25,689 - INFO - 作業成功完成！
2025-01-12 20:43:58,513 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 20:44:10,903 - INFO - 完成【更新漢字注音作業程序】...
2025-01-12 20:44:10,904 - INFO - 完成【處理作業】...
2025-01-12 20:44:10,998 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 20:44:10,998 - INFO - 作業成功完成！
2025-01-12 20:54:52,750 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 20:54:52,872 - INFO - 開始【處理作業】...
2025-01-12 20:54:53,119 - ERROR - 執行過程中發生未知錯誤: All elements of a 2d list or tuple must be of the same length
Traceback (most recent call last):
  File "a000.py", line 275, in main
    result_code = process(wb)
  File "a000.py", line 229, in process
    return_code = ca_han_ji_thak_im(wb)
  File "a000.py", line 127, in ca_han_ji_thak_im
    maintain_han_ji_koo(sheet=han_ji_koo_sheet,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
                        han_ji=han_ji, tai_gi=tai_gi,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        show_msg=False)
                        ^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_excel_access.py", line 115, in maintain_han_ji_koo
    sheet.range("A2").value = records  # 寫入更新後的資料
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2482, in value
    conversion.write(data, self, self._options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\conversion\__init__.py", line 94, in write
    raise Exception(
        "All elements of a 2d list or tuple must be of the same length"
    )
Exception: All elements of a 2d list or tuple must be of the same length
2025-01-12 20:54:53,211 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 20:55:23,600 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 20:55:23,712 - INFO - 開始【處理作業】...
2025-01-12 20:56:06,343 - INFO - 完成【作業程序】：查找漢字注音...
2025-01-12 20:56:40,252 - ERROR - 執行過程中發生未知錯誤: list index out of range
Traceback (most recent call last):
  File "a000.py", line 275, in main
    result_code = process(wb)
  File "a000.py", line 234, in process
    return_code = update_han_ji_piau_im(wb)
  File "a000.py", line 177, in update_han_ji_piau_im
    corrected_tai_gi = row[3] or ""
                       ~~~^^^
IndexError: list index out of range
2025-01-12 20:56:40,360 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 20:58:01,479 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 20:58:29,406 - ERROR - 執行過程中發生未知錯誤: list index out of range
Traceback (most recent call last):
  File "a000.py", line 275, in main
    result_code = process(wb)
  File "a000.py", line 234, in process
    return_code = update_han_ji_piau_im(wb)
  File "a000.py", line 177, in update_han_ji_piau_im
    corrected_tai_gi = row[3] or ""
                       ~~~^^^
IndexError: list index out of range
2025-01-12 20:58:29,513 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 20:58:59,426 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 21:00:20,790 - ERROR - 執行過程中發生未知錯誤: list index out of range
Traceback (most recent call last):
  File "a000.py", line 275, in main
    result_code = process(wb)
  File "a000.py", line 234, in process
    return_code = update_han_ji_piau_im(wb)
  File "a000.py", line 177, in update_han_ji_piau_im
    corrected_tai_gi = row[3] or ""
                       ~~~^^^
IndexError: list index out of range
2025-01-12 21:00:20,881 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 21:00:26,713 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 21:02:18,381 - ERROR - 執行過程中發生未知錯誤: list index out of range
Traceback (most recent call last):
  File "a000.py", line 275, in main
    result_code = process(wb)
  File "a000.py", line 234, in process
    return_code = update_han_ji_piau_im(wb)
  File "a000.py", line 177, in update_han_ji_piau_im
    corrected_tai_gi = row[3] or ""
                       ~~~^^^
IndexError: list index out of range
2025-01-12 21:02:18,508 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 21:03:10,235 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 21:11:19,089 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 21:14:39,721 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 21:14:46,135 - INFO - 處理作業失敗，過程中出錯！
2025-01-12 21:14:46,135 - INFO - 處理作業失敗，過程中出錯！
2025-01-12 21:14:46,291 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 21:14:58,761 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 21:15:07,863 - INFO - 處理作業失敗，過程中出錯！
2025-01-12 21:15:07,863 - INFO - 處理作業失敗，過程中出錯！
2025-01-12 21:15:07,944 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 21:16:57,151 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 21:19:18,635 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 21:19:32,313 - INFO - 完成【處理作業】...
2025-01-12 21:22:25,843 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 21:22:29,312 - INFO - 完成【處理作業】...
2025-01-12 21:22:29,409 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 21:22:29,409 - INFO - 作業成功完成！
2025-01-12 21:23:06,195 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 21:23:06,294 - INFO - 開始【處理作業】...
2025-01-12 21:23:48,041 - INFO - 完成【作業程序】：查找漢字注音...
2025-01-12 21:25:06,751 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 21:25:06,905 - INFO - 開始【處理作業】...
2025-01-12 21:25:48,737 - INFO - 完成【作業程序】：查找漢字注音...
2025-01-12 21:27:15,316 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 21:27:15,419 - INFO - 開始【處理作業】...
2025-01-12 21:27:57,268 - INFO - 完成【作業程序】：查找漢字注音...
2025-01-12 21:29:05,738 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 21:29:05,835 - INFO - 開始【處理作業】...
2025-01-12 21:29:47,606 - INFO - 完成【作業程序】：查找漢字注音...
2025-01-12 21:35:04,478 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 21:37:38,323 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 21:40:53,780 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 21:49:35,390 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 21:50:59,448 - INFO - 完成【作業程序】：更新漢字標音...
2025-01-12 21:50:59,448 - INFO - 完成【處理作業】...
2025-01-12 21:50:59,530 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 21:50:59,530 - INFO - 作業成功完成！
2025-01-12 22:01:37,198 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 22:06:38,788 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 22:10:14,471 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 22:12:06,846 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 22:13:07,139 - INFO - 完成【作業程序】：更新漢字標音...
2025-01-12 22:13:07,139 - INFO - 完成【處理作業】...
2025-01-12 22:13:07,219 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 22:13:07,219 - INFO - 作業成功完成！
2025-01-12 22:40:05,978 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 22:40:06,071 - INFO - 開始【處理作業】...
2025-01-12 22:40:08,715 - INFO - 已更新【待注音漢字】儲存格！
2025-01-12 22:40:08,733 - INFO - 【待注音漢字】總字數為: 143
2025-01-12 22:40:08,888 - INFO - 儲存格內容清除完畢
2025-01-12 22:40:16,243 - INFO - 儲存格格式重設完畢
2025-01-12 22:40:32,873 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-12 22:40:32,909 - INFO - 開始【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-12 22:40:49,225 - ERROR - 執行過程中發生未知錯誤: All elements of a 2d list or tuple must be of the same length
Traceback (most recent call last):
  File "a705_依漢字注音工作表內容更新待注音漢字.py", line 192, in main
    result_code = process(wb)
  File "a705_依漢字注音工作表內容更新待注音漢字.py", line 152, in process
    fill_hanji_in_cells(wb)
    ~~~~~~~~~~~~~~~~~~~^^^^
  File "c:\work\Piau-Im\a701_作業中活頁檔填入漢字.py", line 98, in process
    ca_han_ji_thak_im(wb, sheet_name='漢字注音', cell='V3',
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      ue_im_lui_piat=ue_im_lui_piat,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      han_ji_khoo=han_ji_khoo, db_name=db_name,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      module_name=module_name,
                      ^^^^^^^^^^^^^^^^^^^^^^^^
                      function_name='han_ji_ca_piau_im')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\p702_Ca_Han_Ji_Thak_Im.py", line 240, in ca_han_ji_thak_im
    maintain_han_ji_koo(sheet=han_ji_koo_sheet,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
                        han_ji=han_ji,
                        ^^^^^^^^^^^^^^
                        tai_gi=tai_gi_im_piau,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        show_msg=False)
                        ^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_excel_access.py", line 115, in maintain_han_ji_koo
    sheet.range("A2").value = records  # 寫入更新後的資料
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2482, in value
    conversion.write(data, self, self._options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\conversion\__init__.py", line 94, in write
    raise Exception(
        "All elements of a 2d list or tuple must be of the same length"
    )
Exception: All elements of a 2d list or tuple must be of the same length
2025-01-12 22:40:49,299 - INFO - 釋放 Excel 資源，處理完成。
2025-01-12 22:43:54,629 - INFO - 作業開始
2025-01-12 22:43:54,630 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 22:44:58,447 - INFO - 己存檔至路徑：{file_path}
2025-01-12 22:44:58,447 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-12 22:44:58,447 - INFO - 作業完成！
2025-01-12 22:46:38,119 - INFO - 作業開始
2025-01-12 22:46:38,120 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-12 22:47:21,217 - ERROR - 作業過程發生未知的異常錯誤: All elements of a 2d list or tuple must be of the same length
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 148, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 66, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name="han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\work\Piau-Im\p702_Ca_Han_Ji_Thak_Im.py", line 240, in ca_han_ji_thak_im
    maintain_han_ji_koo(sheet=han_ji_koo_sheet,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
                        han_ji=han_ji,
                        ^^^^^^^^^^^^^^
                        tai_gi=tai_gi_im_piau,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        show_msg=False)
                        ^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_excel_access.py", line 115, in maintain_han_ji_koo
    sheet.range("A2").value = records  # 寫入更新後的資料
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2482, in value
    conversion.write(data, self, self._options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\conversion\__init__.py", line 94, in write
    raise Exception(
        "All elements of a 2d list or tuple must be of the same length"
    )
Exception: All elements of a 2d list or tuple must be of the same length
2025-01-12 22:47:21,222 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 13:39:05,240 - INFO - 作業開始
2025-01-13 13:39:05,241 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 13:39:58,783 - INFO - 己存檔至路徑：{file_path}
2025-01-13 13:39:58,783 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 13:39:58,783 - INFO - 作業完成！
2025-01-13 13:42:50,107 - INFO - 作業開始
2025-01-13 13:42:50,108 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 13:43:39,438 - INFO - 己存檔至路徑：{file_path}
2025-01-13 13:43:39,438 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 13:43:39,438 - INFO - 作業完成！
2025-01-13 13:56:31,356 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 13:56:42,625 - INFO - 完成【作業程序】：更新漢字標音...
2025-01-13 13:56:42,626 - INFO - 完成【處理作業】...
2025-01-13 13:56:42,713 - INFO - 釋放 Excel 資源，處理完成。
2025-01-13 13:56:42,713 - INFO - 作業成功完成！
2025-01-13 13:57:57,473 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 14:00:12,492 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 14:07:03,270 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 14:11:58,627 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 14:13:30,908 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 14:13:49,397 - INFO - 完成【作業程序】：更新漢字標音...
2025-01-13 14:13:49,397 - INFO - 完成【處理作業】...
2025-01-13 14:13:49,468 - INFO - 釋放 Excel 資源，處理完成。
2025-01-13 14:13:49,468 - INFO - 作業成功完成！
2025-01-13 14:20:57,325 - INFO - 作業開始
2025-01-13 14:20:57,326 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 14:21:29,876 - ERROR - 作業過程發生未知的異常錯誤: All elements of a 2d list or tuple must be of the same length
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 383, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 301, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name="han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "a702_查找及填入漢字標音.py", line 255, in ca_han_ji_thak_im
    maintain_han_ji_koo(sheet=han_ji_koo_sheet,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
                        han_ji=han_ji,
                        ^^^^^^^^^^^^^^
                        tai_gi=tai_gi_im_piau,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        show_msg=False)
                        ^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_excel_access.py", line 125, in maintain_han_ji_koo
    sheet.range("A2").value = records  # 寫入更新後的資料
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2482, in value
    conversion.write(data, self, self._options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\conversion\__init__.py", line 94, in write
    raise Exception(
        "All elements of a 2d list or tuple must be of the same length"
    )
Exception: All elements of a 2d list or tuple must be of the same length
2025-01-13 14:21:29,900 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 14:22:50,766 - INFO - 作業開始
2025-01-13 14:22:50,768 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 14:23:39,826 - INFO - 己存檔至路徑：{file_path}
2025-01-13 14:23:39,826 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 14:23:39,826 - INFO - 作業完成！
2025-01-13 15:24:33,801 - INFO - 作業開始
2025-01-13 15:24:33,803 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 15:25:23,643 - INFO - 己存檔至路徑：{file_path}
2025-01-13 15:25:23,643 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 15:25:23,643 - INFO - 作業完成！
2025-01-13 15:27:24,595 - INFO - 作業開始
2025-01-13 15:27:24,596 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 15:28:14,103 - INFO - 己存檔至路徑：{file_path}
2025-01-13 15:28:14,104 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 15:28:14,104 - INFO - 作業完成！
2025-01-13 15:48:29,297 - INFO - 作業開始
2025-01-13 15:48:29,298 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 15:49:19,690 - INFO - 己存檔至路徑：{file_path}
2025-01-13 15:49:19,690 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 15:49:19,690 - INFO - 作業完成！
2025-01-13 16:01:45,921 - INFO - 作業開始
2025-01-13 16:01:45,922 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 16:02:36,713 - INFO - 己存檔至路徑：{file_path}
2025-01-13 16:02:36,714 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 16:02:36,714 - INFO - 作業完成！
2025-01-13 16:05:06,068 - INFO - 作業開始
2025-01-13 16:05:06,069 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 16:06:14,362 - ERROR - 作業過程發生未知的異常錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 391, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 309, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name="han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "a702_查找及填入漢字標音.py", line 154, in ca_han_ji_thak_im
    sheet.range((row, 1)).select()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2815, in select
    self.impl.select()
    ~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1500, in select
    return self.xl.Select()
           ~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in Select
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
2025-01-13 16:06:14,369 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 16:08:36,117 - INFO - 作業開始
2025-01-13 16:08:36,118 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 16:09:26,548 - INFO - 己存檔至路徑：{file_path}
2025-01-13 16:09:26,548 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 16:09:26,548 - INFO - 作業完成！
2025-01-13 16:22:44,428 - INFO - 作業開始
2025-01-13 16:22:44,430 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 16:23:38,486 - INFO - 己存檔至路徑：{file_path}
2025-01-13 16:23:38,486 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 16:23:38,486 - INFO - 作業完成！
2025-01-13 16:25:17,744 - INFO - 作業開始
2025-01-13 16:25:17,745 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 16:26:12,009 - INFO - 己存檔至路徑：{file_path}
2025-01-13 16:26:12,009 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 16:26:12,009 - INFO - 作業完成！
2025-01-13 16:27:07,971 - INFO - 作業開始
2025-01-13 16:27:07,972 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 16:28:00,615 - INFO - 己存檔至路徑：{file_path}
2025-01-13 16:28:00,615 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 16:28:00,615 - INFO - 作業完成！
2025-01-13 16:37:01,720 - INFO - 作業開始
2025-01-13 16:37:01,721 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 16:37:10,961 - INFO - 己存檔至路徑：{file_path}
2025-01-13 16:37:10,961 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 16:37:10,961 - INFO - 作業完成！
2025-01-13 16:38:34,701 - INFO - 作業開始
2025-01-13 16:38:34,702 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 16:38:43,640 - INFO - 己存檔至路徑：{file_path}
2025-01-13 16:38:43,640 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 16:38:43,640 - INFO - 作業完成！
2025-01-13 16:39:32,976 - INFO - 作業開始
2025-01-13 16:39:32,977 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 16:40:25,447 - INFO - 己存檔至路徑：{file_path}
2025-01-13 16:40:25,447 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 16:40:25,447 - INFO - 作業完成！
2025-01-13 16:55:04,247 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 16:55:04,267 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, None, None, None, 0, -2147352565), None)
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 198, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 157, in process
    return_code = update_han_ji_piau_im(wb)
  File "a706_手動更正漢字標音.py", line 74, in update_han_ji_piau_im
    han_ji_khoo_sheet = wb.sheets[han_ji_khoo_sheet_name]
                        ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 89, in __getitem__
    return self(key)
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 5218, in __call__
    return Sheet(impl=self.impl(name_or_index))
                      ~~~~~~~~~^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 943, in __call__
    return Sheet(xl=self.xl(name_or_index))
                    ~~~~~~~^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 236, in __call__
    v = self._inner(*args, **kwargs)
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 213, in __call__
    self._oleobj_.Invoke(*allArgs), self._olerepr_.defaultDispatchName, None
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, None, None, None, 0, -2147352565), None)
2025-01-13 16:55:04,337 - INFO - 釋放 Excel 資源，處理完成。
2025-01-13 17:03:41,448 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 17:04:14,021 - INFO - 完成【作業程序】：更新漢字標音...
2025-01-13 17:04:14,021 - INFO - 完成【處理作業】...
2025-01-13 17:04:14,093 - INFO - 釋放 Excel 資源，處理完成。
2025-01-13 17:04:14,093 - INFO - 作業成功完成！
2025-01-13 17:38:12,132 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 17:38:24,208 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-13 17:38:32,786 - INFO - 完成【處理作業】...
2025-01-13 17:38:32,873 - INFO - 釋放 Excel 資源，處理完成。
2025-01-13 17:38:32,873 - INFO - 作業成功完成！
2025-01-13 17:39:53,580 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 17:40:06,203 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-13 17:40:06,203 - INFO - 完成【處理作業】...
2025-01-13 17:40:06,267 - INFO - 釋放 Excel 資源，處理完成。
2025-01-13 17:40:06,267 - INFO - 作業成功完成！
2025-01-13 17:40:37,701 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 17:40:49,702 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-13 17:40:49,702 - INFO - 完成【處理作業】...
2025-01-13 17:40:49,771 - INFO - 釋放 Excel 資源，處理完成。
2025-01-13 17:40:49,771 - INFO - 作業成功完成！
2025-01-13 17:41:47,291 - INFO - 作業開始
2025-01-13 17:41:47,292 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 17:42:40,304 - INFO - 己存檔至路徑：{file_path}
2025-01-13 17:42:40,304 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 17:42:40,304 - INFO - 作業完成！
2025-01-13 17:43:16,699 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 17:49:10,630 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-13 17:49:10,630 - INFO - 完成【處理作業】...
2025-01-13 17:49:10,702 - INFO - 釋放 Excel 資源，處理完成。
2025-01-13 17:49:10,702 - INFO - 作業成功完成！
2025-01-13 17:49:47,360 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 17:49:59,850 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-13 17:49:59,850 - INFO - 完成【處理作業】...
2025-01-13 17:49:59,919 - INFO - 釋放 Excel 資源，處理完成。
2025-01-13 17:49:59,919 - INFO - 作業成功完成！
2025-01-13 19:15:50,215 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 19:17:03,238 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-13 19:17:03,238 - INFO - 完成【處理作業】...
2025-01-13 19:17:03,304 - INFO - 釋放 Excel 資源，處理完成。
2025-01-13 19:17:03,304 - INFO - 作業成功完成！
2025-01-13 19:20:46,362 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 19:20:58,877 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-13 19:20:58,878 - INFO - 完成【處理作業】...
2025-01-13 19:20:58,949 - INFO - 釋放 Excel 資源，處理完成。
2025-01-13 19:20:58,949 - INFO - 作業成功完成！
2025-01-13 20:12:17,982 - INFO - 作業開始
2025-01-13 20:12:17,983 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 20:13:15,446 - INFO - 己存檔至路徑：{file_path}
2025-01-13 20:13:15,446 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 20:13:15,446 - INFO - 作業完成！
2025-01-13 20:13:24,315 - INFO - 作業開始
2025-01-13 20:13:24,316 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 20:14:26,209 - INFO - 己存檔至路徑：{file_path}
2025-01-13 20:14:26,209 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-13 20:14:26,210 - INFO - 作業完成！
2025-01-13 20:15:54,117 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 20:16:06,915 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-13 20:16:06,915 - INFO - 完成【處理作業】...
2025-01-13 20:16:06,976 - INFO - 釋放 Excel 資源，處理完成。
2025-01-13 20:16:06,976 - INFO - 作業成功完成！
2025-01-13 20:17:54,816 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-13 20:18:13,020 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-13 20:18:13,020 - INFO - 完成【處理作業】...
2025-01-13 20:18:13,082 - INFO - 釋放 Excel 資源，處理完成。
2025-01-13 20:18:13,083 - INFO - 作業成功完成！
2025-01-14 11:07:33,528 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 11:07:33,675 - INFO - 處理作業失敗，過程中出錯！
2025-01-14 11:07:33,675 - INFO - 處理作業失敗，過程中出錯！
2025-01-14 11:07:34,218 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 11:09:15,136 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 11:09:15,322 - INFO - 完成【處理作業】...
2025-01-14 11:09:15,456 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 11:09:15,456 - INFO - 作業成功完成！
2025-01-14 11:11:33,346 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 11:12:05,026 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 11:12:26,853 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 11:19:26,854 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 11:20:26,177 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 11:29:41,477 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 11:29:49,628 - ERROR - 執行過程中發生未知錯誤: '十五音'
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 295, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 254, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 186, in update_han_ji_piau_im
    han_ji_piau_im = jin_kang_piau_im_cu_tai_gi(wb=wb,
                                                han_ji=han_ji,
                                                jin_kang_piau_im=jin_kang_piau_im,
                                                piau_im=piau_im,
                                                piau_im_huat=piau_im_huat)
  File "a706_手動更正漢字標音.py", line 96, in jin_kang_piau_im_cu_tai_gi
    han_ji_piau_im = tlpa_tng_han_ji_piau_im(
        piau_im=piau_im,
        piau_im_huat=piau_im_huat,
        tai_gi_im_piau=tai_gi_im_piau
    )
  File "c:\work\Piau-Im\mod_標音.py", line 177, in tlpa_tng_han_ji_piau_im
    han_ji_piau_im = siann_un_tiau_tng_piau_im(
        piau_im,
    ...<3 lines>...
        tiau_ho
    )
  File "c:\work\Piau-Im\mod_標音.py", line 150, in siann_un_tiau_tng_piau_im
    return piau_im.NST_piau_im(siann_bu, un_bu, tiau_ho)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_標音.py", line 768, in NST_piau_im
    un = self.Un_Bu_Dict[un_bu][piau_im_huat]
         ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: '十五音'
2025-01-14 11:29:49,747 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 11:31:10,533 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 11:32:49,740 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 11:34:16,980 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 11:34:47,587 - ERROR - 執行過程中發生未知錯誤: '十五音'
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 295, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 254, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 186, in update_han_ji_piau_im
    han_ji_piau_im = jin_kang_piau_im_cu_tai_gi(wb=wb,
                                                han_ji=han_ji,
                                                jin_kang_piau_im=jin_kang_piau_im,
                                                piau_im=piau_im,
                                                piau_im_huat=piau_im_huat)
  File "a706_手動更正漢字標音.py", line 96, in jin_kang_piau_im_cu_tai_gi
    han_ji_piau_im = tlpa_tng_han_ji_piau_im(
        piau_im=piau_im,
        piau_im_huat=piau_im_huat,
        tai_gi_im_piau=tai_gi_im_piau
    )
  File "c:\work\Piau-Im\mod_標音.py", line 177, in tlpa_tng_han_ji_piau_im
    han_ji_piau_im = siann_un_tiau_tng_piau_im(
        piau_im,
    ...<3 lines>...
        tiau_ho
    )
  File "c:\work\Piau-Im\mod_標音.py", line 150, in siann_un_tiau_tng_piau_im
    return piau_im.NST_piau_im(siann_bu, un_bu, tiau_ho)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_標音.py", line 768, in NST_piau_im
    un = self.Un_Bu_Dict[un_bu][piau_im_huat]
         ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: '十五音'
2025-01-14 11:34:47,721 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 11:36:29,641 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 11:36:52,539 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 11:37:02,865 - ERROR - 執行過程中發生未知錯誤: '十五音'
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 295, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 254, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 186, in update_han_ji_piau_im
    han_ji_piau_im = jin_kang_piau_im_cu_tai_gi(wb=wb,
                                                han_ji=han_ji,
                                                jin_kang_piau_im=jin_kang_piau_im,
                                                piau_im=piau_im,
                                                piau_im_huat=piau_im_huat)
  File "a706_手動更正漢字標音.py", line 96, in jin_kang_piau_im_cu_tai_gi
    han_ji_piau_im = tlpa_tng_han_ji_piau_im(
        piau_im=piau_im,
        piau_im_huat=piau_im_huat,
        tai_gi_im_piau=tai_gi_im_piau
    )
  File "c:\work\Piau-Im\mod_標音.py", line 177, in tlpa_tng_han_ji_piau_im
    han_ji_piau_im = siann_un_tiau_tng_piau_im(
        piau_im,
    ...<3 lines>...
        tiau_ho
    )
  File "c:\work\Piau-Im\mod_標音.py", line 150, in siann_un_tiau_tng_piau_im
    return piau_im.NST_piau_im(siann_bu, un_bu, tiau_ho)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_標音.py", line 768, in NST_piau_im
    un = self.Un_Bu_Dict[un_bu][piau_im_huat]
         ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: '十五音'
2025-01-14 11:37:03,202 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 11:37:46,652 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 11:41:33,411 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 11:43:27,461 - ERROR - 執行過程中發生未知錯誤: '十五音'
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 295, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 254, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 186, in update_han_ji_piau_im
    han_ji_piau_im = jin_kang_piau_im_cu_tai_gi(wb=wb,
                                                han_ji=han_ji,
                                                jin_kang_piau_im=jin_kang_piau_im,
                                                piau_im=piau_im,
                                                piau_im_huat=piau_im_huat)
  File "a706_手動更正漢字標音.py", line 96, in jin_kang_piau_im_cu_tai_gi
    han_ji_piau_im = tlpa_tng_han_ji_piau_im(
        piau_im=piau_im,
        piau_im_huat=piau_im_huat,
        tai_gi_im_piau=tai_gi_im_piau
    )
  File "c:\work\Piau-Im\mod_標音.py", line 177, in tlpa_tng_han_ji_piau_im
    han_ji_piau_im = siann_un_tiau_tng_piau_im(
        piau_im,
    ...<3 lines>...
        tiau_ho
    )
  File "c:\work\Piau-Im\mod_標音.py", line 150, in siann_un_tiau_tng_piau_im
    return piau_im.NST_piau_im(siann_bu, un_bu, tiau_ho)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_標音.py", line 768, in NST_piau_im
    un = self.Un_Bu_Dict[un_bu][piau_im_huat]
         ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: '十五音'
2025-01-14 11:43:27,613 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 11:45:14,303 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 11:47:04,533 - ERROR - 執行過程中發生未知錯誤: '十五音'
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 295, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 254, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 186, in update_han_ji_piau_im
    han_ji_piau_im = jin_kang_piau_im_cu_tai_gi(wb=wb,
                                                han_ji=han_ji,
                                                jin_kang_piau_im=jin_kang_piau_im,
                                                piau_im=piau_im,
                                                piau_im_huat=piau_im_huat)
  File "a706_手動更正漢字標音.py", line 96, in jin_kang_piau_im_cu_tai_gi
    han_ji_piau_im = tlpa_tng_han_ji_piau_im(
        piau_im=piau_im,
        piau_im_huat=piau_im_huat,
        tai_gi_im_piau=tai_gi_im_piau
    )
  File "c:\work\Piau-Im\mod_標音.py", line 177, in tlpa_tng_han_ji_piau_im
    han_ji_piau_im = siann_un_tiau_tng_piau_im(
        piau_im,
    ...<3 lines>...
        tiau_ho
    )
  File "c:\work\Piau-Im\mod_標音.py", line 150, in siann_un_tiau_tng_piau_im
    return piau_im.NST_piau_im(siann_bu, un_bu, tiau_ho)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_標音.py", line 768, in NST_piau_im
    un = self.Un_Bu_Dict[un_bu][piau_im_huat]
         ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: '十五音'
2025-01-14 11:47:04,663 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 11:59:14,454 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 11:59:14,511 - ERROR - 執行過程中發生未知錯誤: no such table: 聲母對照表
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 298, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 257, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 122, in update_han_ji_piau_im
    piau_im = PiauIm(han_ji_khoo=han_ji_khoo_name, cursor=cursor)
  File "c:\work\Piau-Im\mod_標音.py", line 386, in __init__
    self.init_piau_im_dict(han_ji_khoo)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_標音.py", line 474, in init_piau_im_dict
    self.Siann_Bu_Dict = self._init_siann_bu_dict()
                         ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\mod_標音.py", line 436, in _init_siann_bu_dict
    self.cursor.execute("SELECT * FROM 聲母對照表")
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: 聲母對照表
2025-01-14 11:59:14,636 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 11:59:30,481 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 11:59:30,537 - ERROR - 執行過程中發生未知錯誤: no such table: 聲母對照表
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 298, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 257, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 122, in update_han_ji_piau_im
    piau_im = PiauIm(han_ji_khoo=han_ji_khoo_name, cursor=cursor)
  File "c:\work\Piau-Im\mod_標音.py", line 386, in __init__
    self.init_piau_im_dict(han_ji_khoo)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_標音.py", line 474, in init_piau_im_dict
    self.Siann_Bu_Dict = self._init_siann_bu_dict()
                         ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\mod_標音.py", line 436, in _init_siann_bu_dict
    self.cursor.execute("SELECT * FROM 聲母對照表")
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: 聲母對照表
2025-01-14 11:59:30,659 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 12:00:47,648 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 12:03:19,614 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 12:09:21,791 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 12:27:50,786 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 12:27:51,017 - ERROR - 執行過程中發生未知錯誤: cannot access local variable 'han_ji_piau_im' where it is not associated with a value
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 302, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 261, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 241, in update_han_ji_piau_im
    print(f"({row}, {xw.utils.col_name(col)}) = {han_ji}，台語音標【{tai_gi_piau_im}】/【{han_ji_piau_im}】{msg_tail}")
                                                                                          ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'han_ji_piau_im' where it is not associated with a value
2025-01-14 12:27:51,163 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 12:28:16,114 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 12:28:16,348 - ERROR - 執行過程中發生未知錯誤: cannot access local variable 'han_ji_piau_im' where it is not associated with a value
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 302, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 261, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 241, in update_han_ji_piau_im
    print(f"({row}, {xw.utils.col_name(col)}) = {han_ji}，台語音標【{tai_gi_piau_im}】/【{han_ji_piau_im}】{msg_tail}")
                                                                                          ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'han_ji_piau_im' where it is not associated with a value
2025-01-14 12:28:16,489 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 12:30:08,149 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 12:30:47,326 - ERROR - 執行過程中發生未知錯誤: cannot access local variable 'han_ji_piau_im' where it is not associated with a value
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 302, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 261, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 241, in update_han_ji_piau_im
    print(f"({row}, {xw.utils.col_name(col)}) = {han_ji}，台語音標【{tai_gi_piau_im}】/【{han_ji_piau_im}】{msg_tail}")
                                                                                          ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'han_ji_piau_im' where it is not associated with a value
2025-01-14 12:30:47,481 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 12:32:19,499 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:11:00,041 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:11:00,241 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 321, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 280, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 172, in update_han_ji_piau_im
    sheet.range((row, 1)).select()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2815, in select
    self.impl.select()
    ~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1500, in select
    return self.xl.Select()
           ~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in Select
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
2025-01-14 13:11:00,404 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 13:11:23,031 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:11:23,212 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 321, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 280, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 172, in update_han_ji_piau_im
    sheet.range((row, 1)).select()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2815, in select
    self.impl.select()
    ~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1500, in select
    return self.xl.Select()
           ~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in Select
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
2025-01-14 13:11:23,339 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 13:12:07,419 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:12:21,870 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 321, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 280, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 172, in update_han_ji_piau_im
    sheet.range((row, 1)).select()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2815, in select
    self.impl.select()
    ~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1500, in select
    return self.xl.Select()
           ~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in Select
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
2025-01-14 13:12:22,010 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 13:13:33,776 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:14:08,245 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 321, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 280, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 172, in update_han_ji_piau_im
    sheet.range((row, 1)).select()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2815, in select
    self.impl.select()
    ~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1500, in select
    return self.xl.Select()
           ~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in Select
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
2025-01-14 13:14:08,401 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 13:16:57,141 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:17:06,990 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 321, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 280, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 172, in update_han_ji_piau_im
    sheet.range((row, 1)).select()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2815, in select
    self.impl.select()
    ~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1500, in select
    return self.xl.Select()
           ~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in Select
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
2025-01-14 13:17:07,123 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 13:18:12,853 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:24:28,437 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:27:03,839 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:31:22,827 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:32:53,238 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:33:45,925 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:35:37,531 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:37:42,151 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:40:13,342 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:40:57,233 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:42:20,890 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:46:07,372 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:47:54,035 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:48:26,488 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:51:19,399 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 13:57:02,635 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:01:19,915 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:03:57,154 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:04:54,099 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:06:56,930 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:15:57,377 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:17:19,378 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:19:38,118 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:19:53,474 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:21:31,321 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:21:57,000 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:22:42,880 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:24:28,205 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:27:22,922 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 14:28:24,526 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:33:38,644 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:35:58,776 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:37:24,492 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:40:11,114 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:41:41,894 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:50:06,048 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:50:06,271 - ERROR - 執行過程中發生未知錯誤: 'bool' object is not callable
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 332, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 291, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 193, in update_han_ji_piau_im
    if is_punctuation(han_ji):
       ~~~~~~~~~~~~~~^^^^^^^^
TypeError: 'bool' object is not callable
2025-01-14 14:50:06,420 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 14:53:34,356 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 14:56:33,825 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 15:00:08,193 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 15:02:09,097 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 15:04:00,497 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 15:07:29,353 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 15:10:34,519 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 15:12:02,643 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 15:13:09,453 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 15:13:25,628 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-14 15:13:25,628 - INFO - 完成【處理作業】...
2025-01-14 15:13:25,813 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 15:13:25,813 - INFO - 作業成功完成！
2025-01-14 15:13:45,460 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 15:14:11,836 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-14 15:14:11,836 - INFO - 完成【處理作業】...
2025-01-14 15:14:12,045 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 15:14:12,045 - INFO - 作業成功完成！
2025-01-14 15:15:55,174 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 15:16:16,804 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-14 15:16:16,805 - INFO - 完成【處理作業】...
2025-01-14 15:16:16,985 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 15:16:16,985 - INFO - 作業成功完成！
2025-01-14 15:17:08,152 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 15:17:08,333 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 334, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 293, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 170, in update_han_ji_piau_im
    han_ji_piau_im_sheet.range((row, 1)).select()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2815, in select
    self.impl.select()
    ~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1500, in select
    return self.xl.Select()
           ~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in Select
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
2025-01-14 15:17:08,481 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 15:18:16,909 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 15:18:28,388 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-14 15:18:28,389 - INFO - 完成【處理作業】...
2025-01-14 15:18:28,545 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 15:18:28,545 - INFO - 作業成功完成！
2025-01-14 15:19:00,112 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 15:19:10,548 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-14 15:19:10,548 - INFO - 完成【處理作業】...
2025-01-14 15:19:10,720 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 15:19:10,720 - INFO - 作業成功完成！
2025-01-14 15:54:34,895 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 15:54:45,516 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-14 15:54:45,516 - INFO - 完成【處理作業】...
2025-01-14 15:54:45,674 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 15:54:45,674 - INFO - 作業成功完成！
2025-01-14 15:56:40,528 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 15:56:40,920 - ERROR - 執行過程中發生未知錯誤: 'str' object has no attribute 'value' and no __dict__ for setting new attributes
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 337, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 296, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 252, in update_han_ji_piau_im
    jin_kang_piau_im.value = corrected_tai_gi  # 更新【人工標音】儲存格
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'value' and no __dict__ for setting new attributes
2025-01-14 15:56:41,078 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 15:59:20,146 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 15:59:30,625 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-14 15:59:30,625 - INFO - 完成【處理作業】...
2025-01-14 15:59:30,813 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 15:59:30,813 - INFO - 作業成功完成！
2025-01-14 16:02:20,636 - INFO - 作業開始
2025-01-14 16:02:20,637 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 16:03:21,293 - INFO - 己存檔至路徑：{file_path}
2025-01-14 16:03:21,293 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-14 16:03:21,293 - INFO - 作業完成！
2025-01-14 16:08:47,416 - INFO - 作業開始
2025-01-14 16:08:47,417 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 16:09:46,383 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-14 16:10:11,081 - INFO - 作業開始
2025-01-14 16:10:11,082 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 16:11:10,355 - INFO - 己存檔至路徑：{file_path}
2025-01-14 16:11:10,355 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-14 16:11:10,355 - INFO - 作業完成！
2025-01-14 16:13:49,550 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 16:13:58,819 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-14 16:13:58,820 - INFO - 完成【處理作業】...
2025-01-14 16:13:58,895 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 16:13:58,895 - INFO - 作業成功完成！
2025-01-14 16:14:17,637 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 16:14:27,598 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-14 16:14:27,598 - INFO - 完成【處理作業】...
2025-01-14 16:14:27,671 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 16:14:27,671 - INFO - 作業成功完成！
2025-01-14 16:15:34,597 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 16:15:44,502 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-14 16:15:44,502 - INFO - 完成【處理作業】...
2025-01-14 16:15:44,581 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 16:15:44,581 - INFO - 作業成功完成！
2025-01-14 16:16:40,231 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 16:16:50,102 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-14 16:16:50,102 - INFO - 完成【處理作業】...
2025-01-14 16:16:50,177 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 16:16:50,177 - INFO - 作業成功完成！
2025-01-14 16:19:25,391 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 16:19:35,062 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-14 16:19:35,062 - INFO - 完成【處理作業】...
2025-01-14 16:19:35,144 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 16:19:35,144 - INFO - 作業成功完成！
2025-01-14 16:20:19,947 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 16:20:29,948 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-14 16:20:29,948 - INFO - 完成【處理作業】...
2025-01-14 16:20:30,032 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 16:20:30,032 - INFO - 作業成功完成！
2025-01-14 16:29:15,044 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 16:29:24,256 - ERROR - 執行過程中發生未知錯誤: cannot access local variable 'jin_kang_piau_im_cell' where it is not associated with a value
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 341, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 300, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 202, in update_han_ji_piau_im
    if han_ji_cell.color == (0, 255, 200) and jin_kang_piau_im_cell.value == tai_gi_cell.value:
                                              ^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'jin_kang_piau_im_cell' where it is not associated with a value
2025-01-14 16:29:24,318 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 16:31:49,655 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 16:34:40,292 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 16:35:33,827 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 16:36:17,909 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 16:36:28,342 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-14 16:36:28,342 - INFO - 完成【處理作業】...
2025-01-14 16:36:28,413 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 16:36:28,413 - INFO - 作業成功完成！
2025-01-14 16:36:42,856 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 16:36:52,688 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-14 16:36:52,689 - INFO - 完成【處理作業】...
2025-01-14 16:36:52,760 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 16:36:52,760 - INFO - 作業成功完成！
2025-01-14 16:37:08,328 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 16:37:19,124 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-14 16:37:19,124 - INFO - 完成【處理作業】...
2025-01-14 16:37:19,207 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 16:37:19,207 - INFO - 作業成功完成！
2025-01-14 16:38:09,805 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 16:38:19,995 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-14 16:38:19,996 - INFO - 完成【處理作業】...
2025-01-14 16:38:20,067 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 16:38:20,067 - INFO - 作業成功完成！
2025-01-14 16:38:53,854 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-14 16:39:04,773 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-14 16:39:04,774 - INFO - 完成【處理作業】...
2025-01-14 16:39:04,853 - INFO - 釋放 Excel 資源，處理完成。
2025-01-14 16:39:04,853 - INFO - 作業成功完成！
2025-01-15 11:21:34,007 - INFO - 作業開始
2025-01-15 11:21:34,009 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 11:21:34,045 - INFO - 【待注音漢字】總字數為: 143
2025-01-15 11:21:34,154 - INFO - 儲存格內容清除完畢
2025-01-15 11:21:41,774 - INFO - 儲存格格式重設完畢
2025-01-15 11:21:53,851 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-15 11:21:53,887 - INFO - 開始【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-15 11:22:43,537 - INFO - 完成【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-15 11:22:45,558 - INFO - 儲存檔案至路徑：.\output7\【河洛白話注音-雅俗通】《TestCase》.xlsx
2025-01-15 11:22:45,558 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-15 11:23:01,238 - INFO - 作業開始
2025-01-15 11:23:01,240 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 11:23:01,388 - INFO - 開始【漢字注音】工作表的清空、重置！
2025-01-15 11:23:07,559 - INFO - 完成【漢字注音】工作表的清空、重置！
2025-01-15 11:23:07,741 - INFO - 儲存檔案至路徑：.\output7\【河洛白話注音-雅俗通】《TestCase》.xlsx
2025-01-15 11:23:07,741 - INFO - a700_重罝漢字標音工作表.py 程式已執行完畢！
2025-01-15 11:23:30,214 - INFO - 儲存檔案至路徑：.\output7\【河洛白話注音-雅俗通】_working.xlsx.xlsx
2025-01-15 12:01:11,568 - INFO - 作業開始
2025-01-15 12:01:11,569 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 12:01:11,603 - INFO - 【待注音漢字】總字數為: 448
2025-01-15 12:01:11,695 - INFO - 儲存格內容清除完畢
2025-01-15 12:01:17,865 - INFO - 儲存格格式重設完畢
2025-01-15 12:01:49,825 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-15 12:01:49,865 - INFO - 開始【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-15 12:02:50,534 - ERROR - 作業過程發生未知的異常錯誤: 'ir'
Traceback (most recent call last):
  File "a701_作業中活頁檔填入漢字.py", line 154, in main
    result_code = process(wb)
  File "a701_作業中活頁檔填入漢字.py", line 98, in process
    ca_han_ji_thak_im(wb, sheet_name='漢字注音', cell='V3',
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      ue_im_lui_piat=ue_im_lui_piat,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      han_ji_khoo=han_ji_khoo, db_name=db_name,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      module_name=module_name,
                      ^^^^^^^^^^^^^^^^^^^^^^^^
                      function_name='han_ji_ca_piau_im')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\p702_Ca_Han_Ji_Thak_Im.py", line 231, in ca_han_ji_thak_im
    tai_gi_im_piau, han_ji_piau_im = za_ji_kiat_ko_cut_piau_im(
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~^
        result=result,
        ^^^^^^^^^^^^^^
    ...<2 lines>...
        piau_im_huat=piau_im_huat
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\work\Piau-Im\p702_Ca_Han_Ji_Thak_Im.py", line 73, in za_ji_kiat_ko_cut_piau_im
    han_ji_piau_im = siann_un_tiau_tng_piau_im(
        piau_im,
    ...<3 lines>...
        tiau_ho
    )
  File "c:\work\Piau-Im\mod_標音.py", line 150, in siann_un_tiau_tng_piau_im
    return piau_im.NST_piau_im(siann_bu, un_bu, tiau_ho)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_標音.py", line 786, in NST_piau_im
    un = self.Un_Bu_Dict[un_bu][piau_im_huat]
         ~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'ir'
2025-01-15 12:02:50,539 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-15 13:43:56,793 - INFO - 作業開始
2025-01-15 13:43:56,795 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 13:43:56,829 - INFO - 【待注音漢字】總字數為: 448
2025-01-15 13:43:56,924 - INFO - 儲存格內容清除完畢
2025-01-15 13:44:03,133 - INFO - 儲存格格式重設完畢
2025-01-15 13:44:34,248 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-15 13:44:34,284 - INFO - 開始【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-15 13:46:53,322 - INFO - 完成【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-15 13:46:53,517 - INFO - 儲存檔案至路徑：.\output7\【河洛文讀注音-雅俗通】《岳陽樓記》.xlsx
2025-01-15 13:46:53,517 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-15 14:07:13,486 - INFO - 作業開始
2025-01-15 14:07:13,488 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 14:08:17,628 - ERROR - 作業過程發生未知的異常錯誤: All elements of a 2d list or tuple must be of the same length
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 459, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 388, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name=function_name     # "han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "a702_查找及填入漢字標音.py", line 311, in ca_han_ji_thak_im
    maintain_han_ji_koo(sheet=khuat_ji_piau_im_sheet,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        han_ji=han_ji,
                        ^^^^^^^^^^^^^^
                        tai_gi='',
                        ^^^^^^^^^^
                        show_msg=False)
                        ^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_excel_access.py", line 143, in maintain_han_ji_koo
    sheet.range("A2").value = records  # 寫入更新後的資料
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2482, in value
    conversion.write(data, self, self._options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\conversion\__init__.py", line 94, in write
    raise Exception(
        "All elements of a 2d list or tuple must be of the same length"
    )
Exception: All elements of a 2d list or tuple must be of the same length
2025-01-15 14:08:17,646 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-15 15:00:40,574 - INFO - 作業開始
2025-01-15 15:00:40,575 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 15:01:45,028 - ERROR - 作業過程發生未知的異常錯誤: All elements of a 2d list or tuple must be of the same length
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 459, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 388, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name=function_name     # "han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "a702_查找及填入漢字標音.py", line 311, in ca_han_ji_thak_im
    maintain_han_ji_koo(sheet=khuat_ji_piau_im_sheet,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        han_ji=han_ji,
                        ^^^^^^^^^^^^^^
                        tai_gi='',
                        ^^^^^^^^^^
                        show_msg=False)
                        ^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_excel_access.py", line 143, in maintain_han_ji_koo
    sheet.range("A2").value = records  # 寫入更新後的資料
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2482, in value
    conversion.write(data, self, self._options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\conversion\__init__.py", line 94, in write
    raise Exception(
        "All elements of a 2d list or tuple must be of the same length"
    )
Exception: All elements of a 2d list or tuple must be of the same length
2025-01-15 15:01:45,034 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-15 15:04:04,993 - INFO - 作業開始
2025-01-15 15:04:04,994 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 15:05:09,025 - ERROR - 作業過程發生未知的異常錯誤: All elements of a 2d list or tuple must be of the same length
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 459, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 388, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name=function_name     # "han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "a702_查找及填入漢字標音.py", line 311, in ca_han_ji_thak_im
    maintain_han_ji_koo(sheet=khuat_ji_piau_im_sheet,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        han_ji=han_ji,
                        ^^^^^^^^^^^^^^
                        tai_gi='',
                        ^^^^^^^^^^
                        show_msg=False)
                        ^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_excel_access.py", line 143, in maintain_han_ji_koo
    sheet.range("A2").value = records  # 寫入更新後的資料
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2482, in value
    conversion.write(data, self, self._options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\conversion\__init__.py", line 94, in write
    raise Exception(
        "All elements of a 2d list or tuple must be of the same length"
    )
Exception: All elements of a 2d list or tuple must be of the same length
2025-01-15 15:05:09,030 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-15 15:10:26,550 - INFO - 作業開始
2025-01-15 15:10:26,551 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 15:11:31,008 - ERROR - 作業過程發生未知的異常錯誤: All elements of a 2d list or tuple must be of the same length
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 459, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 388, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name=function_name     # "han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "a702_查找及填入漢字標音.py", line 311, in ca_han_ji_thak_im
    maintain_han_ji_koo(sheet=khuat_ji_piau_im_sheet,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        han_ji=han_ji,
                        ^^^^^^^^^^^^^^
                        tai_gi='',
                        ^^^^^^^^^^
                        show_msg=False)
                        ^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_excel_access.py", line 143, in maintain_han_ji_koo
    sheet.range("A2").value = records  # 寫入更新後的資料
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2482, in value
    conversion.write(data, self, self._options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\conversion\__init__.py", line 94, in write
    raise Exception(
        "All elements of a 2d list or tuple must be of the same length"
    )
Exception: All elements of a 2d list or tuple must be of the same length
2025-01-15 15:11:31,013 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-15 15:12:23,186 - INFO - 作業開始
2025-01-15 15:12:23,187 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 15:13:27,519 - ERROR - 作業過程發生未知的異常錯誤: All elements of a 2d list or tuple must be of the same length
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 459, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 388, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name=function_name     # "han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "a702_查找及填入漢字標音.py", line 311, in ca_han_ji_thak_im
    maintain_han_ji_koo(sheet=khuat_ji_piau_im_sheet,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        han_ji=han_ji,
                        ^^^^^^^^^^^^^^
                        tai_gi='',
                        ^^^^^^^^^^
                        show_msg=False)
                        ^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_excel_access.py", line 143, in maintain_han_ji_koo
    sheet.range("A2").value = records  # 寫入更新後的資料
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2482, in value
    conversion.write(data, self, self._options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\conversion\__init__.py", line 94, in write
    raise Exception(
        "All elements of a 2d list or tuple must be of the same length"
    )
Exception: All elements of a 2d list or tuple must be of the same length
2025-01-15 15:13:27,524 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-15 15:17:20,142 - INFO - 作業開始
2025-01-15 15:17:20,144 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 15:18:24,321 - ERROR - 作業過程發生未知的異常錯誤: All elements of a 2d list or tuple must be of the same length
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 459, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 388, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name=function_name     # "han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "a702_查找及填入漢字標音.py", line 311, in ca_han_ji_thak_im
    maintain_han_ji_koo(sheet=khuat_ji_piau_im_sheet,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        han_ji=han_ji,
                        ^^^^^^^^^^^^^^
                        tai_gi='',
                        ^^^^^^^^^^
                        show_msg=False)
                        ^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_excel_access.py", line 143, in maintain_han_ji_koo
    sheet.range("A2").value = records  # 寫入更新後的資料
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2482, in value
    conversion.write(data, self, self._options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\conversion\__init__.py", line 94, in write
    raise Exception(
        "All elements of a 2d list or tuple must be of the same length"
    )
Exception: All elements of a 2d list or tuple must be of the same length
2025-01-15 15:18:24,326 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-15 22:30:23,605 - INFO - 作業開始
2025-01-15 22:30:23,606 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 22:31:42,013 - ERROR - 作業過程發生未知的異常錯誤: All elements of a 2d list or tuple must be of the same length
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 459, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 388, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name=function_name     # "han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "a702_查找及填入漢字標音.py", line 311, in ca_han_ji_thak_im
    maintain_han_ji_koo(sheet=khuat_ji_piau_im_sheet,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        han_ji=han_ji,
                        ^^^^^^^^^^^^^^
                        tai_gi='',
                        ^^^^^^^^^^
                        show_msg=False)
                        ^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_excel_access.py", line 143, in maintain_han_ji_koo
    sheet.range("A2").value = records  # 寫入更新後的資料
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2482, in value
    conversion.write(data, self, self._options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\conversion\__init__.py", line 94, in write
    raise Exception(
        "All elements of a 2d list or tuple must be of the same length"
    )
Exception: All elements of a 2d list or tuple must be of the same length
2025-01-15 22:31:42,019 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-15 22:37:43,462 - INFO - 作業開始
2025-01-15 22:37:43,463 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 22:38:28,815 - ERROR - 作業過程發生未知的異常錯誤: han_ji_ca_piau_im() got an unexpected keyword argument 'wb'
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 463, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 392, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name=function_name     # "han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: han_ji_ca_piau_im() got an unexpected keyword argument 'wb'
2025-01-15 22:48:16,526 - INFO - 作業開始
2025-01-15 22:48:16,527 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 22:49:41,047 - INFO - 作業開始
2025-01-15 22:49:41,049 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 22:50:59,909 - ERROR - 作業過程發生未知的異常錯誤: All elements of a 2d list or tuple must be of the same length
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 461, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 390, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name=function_name     # "han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "a702_查找及填入漢字標音.py", line 311, in ca_han_ji_thak_im
    maintain_han_ji_koo(sheet=khuat_ji_piau_im_sheet,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        han_ji=han_ji,
                        ^^^^^^^^^^^^^^
                        tai_gi='',
                        ^^^^^^^^^^
                        show_msg=False)
                        ^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_excel_access.py", line 143, in maintain_han_ji_koo
    sheet.range("A2").value = records  # 寫入更新後的資料
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2482, in value
    conversion.write(data, self, self._options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\conversion\__init__.py", line 94, in write
    raise Exception(
        "All elements of a 2d list or tuple must be of the same length"
    )
Exception: All elements of a 2d list or tuple must be of the same length
2025-01-15 22:50:59,914 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-15 22:55:02,692 - INFO - 作業開始
2025-01-15 22:55:02,693 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 22:59:57,798 - ERROR - 作業過程發生未知的異常錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 461, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 390, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name=function_name     # "han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "a702_查找及填入漢字標音.py", line 216, in ca_han_ji_thak_im
    sheet.range((row, 1)).select()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2815, in select
    self.impl.select()
    ~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1500, in select
    return self.xl.Select()
           ~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in Select
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
2025-01-15 22:59:57,836 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-15 23:00:25,881 - INFO - 作業開始
2025-01-15 23:00:25,882 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 23:06:29,506 - INFO - 作業開始
2025-01-15 23:06:29,507 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 23:12:05,386 - INFO - 作業開始
2025-01-15 23:12:05,387 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 23:15:18,011 - INFO - 作業開始
2025-01-15 23:15:18,012 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 23:16:46,311 - ERROR - 作業過程發生未知的異常錯誤: All elements of a 2d list or tuple must be of the same length
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 459, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 388, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name=function_name     # "han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "a702_查找及填入漢字標音.py", line 307, in ca_han_ji_thak_im
    maintain_han_ji_koo(sheet=khuat_ji_piau_sheet,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        han_ji=han_ji,
                        ^^^^^^^^^^^^^^
                        tai_gi='',
                        ^^^^^^^^^^
                        show_msg=False)
                        ^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_excel_access.py", line 143, in maintain_han_ji_koo
    sheet.range("A2").value = records  # 寫入更新後的資料
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2482, in value
    conversion.write(data, self, self._options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\conversion\__init__.py", line 94, in write
    raise Exception(
        "All elements of a 2d list or tuple must be of the same length"
    )
Exception: All elements of a 2d list or tuple must be of the same length
2025-01-15 23:16:46,317 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-15 23:22:17,973 - INFO - 作業開始
2025-01-15 23:22:17,974 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 23:25:44,025 - ERROR - 作業過程發生未知的異常錯誤: All elements of a 2d list or tuple must be of the same length
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 457, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 386, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name=function_name     # "han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "a702_查找及填入漢字標音.py", line 303, in ca_han_ji_thak_im
    maintain_han_ji_koo(sheet=khuat_ji_piau_sheet,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        han_ji=han_ji,
                        ^^^^^^^^^^^^^^
                        tai_gi='',
                        ^^^^^^^^^^
                        show_msg=False)
                        ^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_excel_access.py", line 143, in maintain_han_ji_koo
    sheet.range("A2").value = records  # 寫入更新後的資料
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2482, in value
    conversion.write(data, self, self._options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\conversion\__init__.py", line 94, in write
    raise Exception(
        "All elements of a 2d list or tuple must be of the same length"
    )
Exception: All elements of a 2d list or tuple must be of the same length
2025-01-15 23:25:44,032 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-15 23:25:55,022 - INFO - 作業開始
2025-01-15 23:25:55,023 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 23:29:08,191 - ERROR - 作業過程發生未知的異常錯誤: All elements of a 2d list or tuple must be of the same length
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 457, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 386, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name=function_name     # "han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "a702_查找及填入漢字標音.py", line 303, in ca_han_ji_thak_im
    maintain_han_ji_koo(sheet=khuat_ji_piau_sheet,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        han_ji=han_ji,
                        ^^^^^^^^^^^^^^
                        tai_gi='',
                        ^^^^^^^^^^
                        show_msg=False)
                        ^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_excel_access.py", line 143, in maintain_han_ji_koo
    sheet.range("A2").value = records  # 寫入更新後的資料
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2482, in value
    conversion.write(data, self, self._options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\conversion\__init__.py", line 94, in write
    raise Exception(
        "All elements of a 2d list or tuple must be of the same length"
    )
Exception: All elements of a 2d list or tuple must be of the same length
2025-01-15 23:29:08,197 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-15 23:29:46,657 - INFO - 作業開始
2025-01-15 23:29:46,659 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-15 23:36:18,081 - ERROR - 作業過程發生未知的異常錯誤: All elements of a 2d list or tuple must be of the same length
Traceback (most recent call last):
  File "a702_查找及填入漢字標音.py", line 457, in main
    result_code = process(wb)
  File "a702_查找及填入漢字標音.py", line 386, in process
    ca_han_ji_thak_im(
    ~~~~~~~~~~~~~~~~~^
        wb=wb,
        ^^^^^^
    ...<6 lines>...
        function_name=function_name     # "han_ji_ca_piau_im",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "a702_查找及填入漢字標音.py", line 303, in ca_han_ji_thak_im
    maintain_han_ji_koo(sheet=khuat_ji_piau_sheet,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        han_ji=han_ji,
                        ^^^^^^^^^^^^^^
                        tai_gi='',
                        ^^^^^^^^^^
                        show_msg=False)
                        ^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_excel_access.py", line 143, in maintain_han_ji_koo
    sheet.range("A2").value = records  # 寫入更新後的資料
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2482, in value
    conversion.write(data, self, self._options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\conversion\__init__.py", line 94, in write
    raise Exception(
        "All elements of a 2d list or tuple must be of the same length"
    )
Exception: All elements of a 2d list or tuple must be of the same length
2025-01-15 23:36:18,136 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-16 10:23:33,511 - INFO - 作業開始
2025-01-16 10:23:33,513 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 10:24:45,509 - INFO - 作業開始
2025-01-16 10:24:45,511 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 10:27:13,391 - INFO - 作業開始
2025-01-16 10:27:13,392 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 10:30:05,879 - INFO - 己存檔至路徑：{file_path}
2025-01-16 10:30:05,879 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-16 10:30:05,879 - INFO - 作業完成！
2025-01-16 10:50:36,845 - INFO - 作業開始
2025-01-16 10:50:36,846 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 10:50:41,728 - ERROR - 作業過程發生未知的異常錯誤: No such file: 'Test_Case_Sample.xlsx'
Traceback (most recent call last):
  File "mod_excel_access.py", line 419, in main
    result_code = process(wb)
  File "mod_excel_access.py", line 362, in process
    return_code = ut_khuat_ji_piau(wb=wb)
  File "mod_excel_access.py", line 233, in ut_khuat_ji_piau
    wb = xw.Book('Test_Case_Sample.xlsx')
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 933, in __init__
    impl = app.books.open(
           ~~~~~~~~~~~~~~^
        fullname,
        ^^^^^^^^^
    ...<13 lines>...
        corrupt_load,
        ^^^^^^^^^^^^^
    ).impl
    ^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 5157, in open
    raise FileNotFoundError("No such file: '%s'" % fullname)
FileNotFoundError: No such file: 'Test_Case_Sample.xlsx'
2025-01-16 10:50:41,733 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-16 10:53:22,021 - INFO - 作業開始
2025-01-16 10:53:22,022 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 11:30:17,597 - INFO - 作業開始
2025-01-16 11:30:17,598 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 11:30:56,788 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-16 11:31:53,851 - INFO - 作業開始
2025-01-16 11:31:53,852 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 11:31:59,211 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-16 11:33:23,114 - INFO - 作業開始
2025-01-16 11:33:23,115 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 11:36:19,031 - INFO - 己存檔至路徑：{file_path}
2025-01-16 11:36:19,031 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-16 11:36:19,031 - INFO - 作業完成！
2025-01-16 12:47:28,585 - INFO - 作業開始
2025-01-16 12:47:28,586 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 12:47:28,626 - INFO - 【待注音漢字】總字數為: 448
2025-01-16 12:47:28,877 - INFO - 儲存格內容清除完畢
2025-01-16 12:47:36,149 - INFO - 儲存格格式重設完畢
2025-01-16 12:48:16,801 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-16 12:48:16,839 - INFO - 開始【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-16 12:51:33,760 - INFO - 完成【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-16 12:51:34,021 - INFO - 儲存檔案至路徑：.\output7\【河洛文讀注音-雅俗通】《岳陽樓記》.xlsx
2025-01-16 12:51:34,022 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-16 13:50:17,556 - INFO - 作業開始
2025-01-16 13:50:17,557 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 13:50:18,345 - INFO - 作業異常終止！
2025-01-16 13:50:18,345 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-16 13:51:11,359 - INFO - 作業開始
2025-01-16 13:51:11,360 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 13:52:36,432 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-16 13:53:27,174 - INFO - 作業開始
2025-01-16 13:53:27,175 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 13:53:49,737 - INFO - 作業開始
2025-01-16 13:53:49,738 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 13:59:16,307 - INFO - 作業開始
2025-01-16 13:59:16,308 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 13:59:16,923 - INFO - 作業異常終止！
2025-01-16 13:59:52,781 - INFO - 作業開始
2025-01-16 13:59:52,782 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 13:59:53,289 - INFO - 作業異常終止！
2025-01-16 14:00:46,515 - INFO - 作業開始
2025-01-16 14:00:46,516 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 14:00:47,026 - INFO - 作業異常終止！
2025-01-16 14:01:18,722 - INFO - 作業開始
2025-01-16 14:01:18,723 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 14:02:32,874 - INFO - 作業開始
2025-01-16 14:02:32,876 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 14:04:31,825 - INFO - 作業開始
2025-01-16 14:04:31,826 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 14:04:41,758 - INFO - 作業異常終止！
2025-01-16 14:05:26,646 - INFO - 作業開始
2025-01-16 14:05:26,647 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 14:06:40,849 - INFO - 作業開始
2025-01-16 14:06:40,850 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 14:07:10,028 - ERROR - 作業過程發生未知的異常錯誤: (-2147352567, '發生例外狀況。', (0, None, None, None, 0, -2147352565), None)
Traceback (most recent call last):
  File "mod_excel_access.py", line 471, in main
    result_code = process(wb)
  File "mod_excel_access.py", line 410, in process
    han_ji_dict = create_dict_by_sheet(wb, "缺字庫")
                  ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "mod_excel_access.py", line 184, in create_dict_by_sheet
    ji_khoo_sheet = wb.sheets[sheet_name]
                    ~~~~~~~~~^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 89, in __getitem__
    return self(key)
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 5218, in __call__
    return Sheet(impl=self.impl(name_or_index))
                      ~~~~~~~~~^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 943, in __call__
    return Sheet(xl=self.xl(name_or_index))
                    ~~~~~~~^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 236, in __call__
    v = self._inner(*args, **kwargs)
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 213, in __call__
    self._oleobj_.Invoke(*allArgs), self._olerepr_.defaultDispatchName, None
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, None, None, None, 0, -2147352565), None)
2025-01-16 14:07:41,756 - INFO - 作業開始
2025-01-16 14:07:41,757 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 14:09:50,196 - INFO - 作業開始
2025-01-16 14:09:50,197 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 14:10:17,717 - ERROR - 作業過程發生未知的異常錯誤: (-2147352567, '發生例外狀況。', (0, None, None, None, 0, -2147352565), None)
Traceback (most recent call last):
  File "mod_excel_access.py", line 471, in main
    result_code = process(wb)
  File "mod_excel_access.py", line 410, in process
    han_ji_dict = create_dict_by_sheet(wb, "缺字庫")
                  ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "mod_excel_access.py", line 184, in create_dict_by_sheet
    ji_khoo_sheet = wb.sheets[sheet_name]
                    ~~~~~~~~~^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 89, in __getitem__
    return self(key)
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 5218, in __call__
    return Sheet(impl=self.impl(name_or_index))
                      ~~~~~~~~~^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 943, in __call__
    return Sheet(xl=self.xl(name_or_index))
                    ~~~~~~~^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 236, in __call__
    v = self._inner(*args, **kwargs)
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 213, in __call__
    self._oleobj_.Invoke(*allArgs), self._olerepr_.defaultDispatchName, None
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, None, None, None, 0, -2147352565), None)
2025-01-16 14:11:40,686 - INFO - 作業開始
2025-01-16 14:11:40,687 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 14:11:55,981 - ERROR - 作業過程發生未知的異常錯誤: (-2147352567, '發生例外狀況。', (0, None, None, None, 0, -2147352565), None)
Traceback (most recent call last):
  File "mod_excel_access.py", line 471, in main
    result_code = process(wb)
  File "mod_excel_access.py", line 410, in process
    han_ji_dict = create_dict_by_sheet(wb=wb, sheet_name='缺字庫')
                  ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mod_excel_access.py", line 184, in create_dict_by_sheet
    ji_khoo_sheet = wb.sheets[sheet_name]
                    ~~~~~~~~~^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 89, in __getitem__
    return self(key)
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 5218, in __call__
    return Sheet(impl=self.impl(name_or_index))
                      ~~~~~~~~~^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 943, in __call__
    return Sheet(xl=self.xl(name_or_index))
                    ~~~~~~~^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 236, in __call__
    v = self._inner(*args, **kwargs)
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 213, in __call__
    self._oleobj_.Invoke(*allArgs), self._olerepr_.defaultDispatchName, None
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, None, None, None, 0, -2147352565), None)
2025-01-16 14:12:06,857 - INFO - 作業開始
2025-01-16 14:12:06,858 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 14:14:25,605 - INFO - 作業開始
2025-01-16 14:14:25,606 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 14:15:50,511 - INFO - 作業開始
2025-01-16 14:15:50,512 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 14:37:19,104 - INFO - 作業開始
2025-01-16 14:37:19,105 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 14:38:33,325 - INFO - 作業開始
2025-01-16 14:38:33,326 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 14:40:55,917 - INFO - 作業開始
2025-01-16 14:40:55,918 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 14:42:04,902 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 14:42:05,255 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 325, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 284, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 153, in update_han_ji_piau_im
    han_ji_piau_im_sheet.range((row, 1)).select()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2815, in select
    self.impl.select()
    ~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1500, in select
    return self.xl.Select()
           ~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in Select
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
2025-01-16 14:42:05,346 - INFO - 釋放 Excel 資源，處理完成。
2025-01-16 15:12:32,247 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 15:13:06,916 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, None, None, None, 0, -2147352565), None)
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 325, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 284, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 135, in update_han_ji_piau_im
    han_ji_dict = create_dict_by_sheet(wb=wb, sheet_name='人工標音字庫')
                  ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_excel_access.py", line 184, in create_dict_by_sheet
    ji_khoo_sheet = wb.sheets[sheet_name]
                    ~~~~~~~~~^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 89, in __getitem__
    return self(key)
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 5218, in __call__
    return Sheet(impl=self.impl(name_or_index))
                      ~~~~~~~~~^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 943, in __call__
    return Sheet(xl=self.xl(name_or_index))
                    ~~~~~~~^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 236, in __call__
    v = self._inner(*args, **kwargs)
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 213, in __call__
    self._oleobj_.Invoke(*allArgs), self._olerepr_.defaultDispatchName, None
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, None, None, None, 0, -2147352565), None)
2025-01-16 15:13:07,034 - INFO - 釋放 Excel 資源，處理完成。
2025-01-16 15:14:38,794 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 17:14:19,565 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 17:14:25,951 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 342, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 301, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 158, in update_han_ji_piau_im
    han_ji_piau_im_sheet.range((row, 1)).select()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2815, in select
    self.impl.select()
    ~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1500, in select
    return self.xl.Select()
           ~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in Select
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
2025-01-16 17:14:26,018 - INFO - 釋放 Excel 資源，處理完成。
2025-01-16 17:14:35,143 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 17:14:58,777 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 342, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 301, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 158, in update_han_ji_piau_im
    han_ji_piau_im_sheet.range((row, 1)).select()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2815, in select
    self.impl.select()
    ~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1500, in select
    return self.xl.Select()
           ~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in Select
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
2025-01-16 17:14:58,850 - INFO - 釋放 Excel 資源，處理完成。
2025-01-16 17:16:18,746 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 17:16:44,825 - ERROR - 執行過程中發生未知錯誤: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 342, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 301, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 158, in update_han_ji_piau_im
    han_ji_piau_im_sheet.range((row, 1)).select()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 2815, in select
    self.impl.select()
    ~~~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 1500, in select
    return self.xl.Select()
           ~~~~~~~~~~~~~~^^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in Select
  File "c:\work\Piau-Im\.venv\Lib\site-packages\win32com\client\dynamic.py", line 355, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
        *(dispid, LCID, wFlags, retType, argTypes) + args
    )
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'Microsoft Excel', 'Class Range 的 Select 方法失敗', 'xlmain11.chm', 0, -2146827284), None)
2025-01-16 17:16:44,889 - INFO - 釋放 Excel 資源，處理完成。
2025-01-16 17:18:29,046 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 17:22:05,870 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 17:23:17,106 - ERROR - 執行過程中發生未知錯誤: string index out of range
Traceback (most recent call last):
  File "a706_手動更正漢字標音.py", line 343, in main
    result_code = process(wb)
  File "a706_手動更正漢字標音.py", line 302, in process
    return_code = update_han_ji_piau_im(wb=wb)
  File "a706_手動更正漢字標音.py", line 219, in update_han_ji_piau_im
    han_ji_piau_im_cell.value = tlpa_tng_han_ji_piau_im(piau_im=piau_im,
                                ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
                                                        piau_im_huat=piau_im_huat,
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                        tai_gi_im_piau=corrected_tai_gi)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_標音.py", line 264, in tlpa_tng_han_ji_piau_im
    siann_bu, un_bu, tiau_ho = split_tai_gi_im_piau(tai_gi_im_piau)
                               ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "c:\work\Piau-Im\mod_標音.py", line 167, in split_tai_gi_im_piau
    tiau = im_piau[-1]  # 最後一個字符是聲調
           ~~~~~~~^^^^
IndexError: string index out of range
2025-01-16 17:23:17,177 - INFO - 釋放 Excel 資源，處理完成。
2025-01-16 17:23:54,302 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 17:24:22,000 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 17:26:16,728 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 17:36:34,516 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 17:38:01,290 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 17:44:34,738 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 17:45:52,475 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-16 17:45:52,476 - INFO - 完成【處理作業】...
2025-01-16 17:45:52,556 - INFO - 釋放 Excel 資源，處理完成。
2025-01-16 17:45:52,556 - INFO - 作業成功完成！
2025-01-16 18:29:45,304 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 18:30:15,208 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-16 18:30:15,208 - INFO - 完成【處理作業】...
2025-01-16 18:30:15,284 - INFO - 釋放 Excel 資源，處理完成。
2025-01-16 18:30:15,284 - INFO - 作業成功完成！
2025-01-16 18:30:39,730 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 18:31:11,033 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-16 18:31:11,034 - INFO - 完成【處理作業】...
2025-01-16 18:31:11,109 - INFO - 釋放 Excel 資源，處理完成。
2025-01-16 18:31:11,109 - INFO - 作業成功完成！
2025-01-16 19:47:11,419 - INFO - 作業開始
2025-01-16 19:47:11,420 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 19:47:11,453 - INFO - 【待注音漢字】總字數為: 448
2025-01-16 19:47:11,529 - INFO - 儲存格內容清除完畢
2025-01-16 19:47:18,329 - INFO - 儲存格格式重設完畢
2025-01-16 19:47:50,343 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-16 19:47:50,379 - INFO - 開始【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-16 19:50:09,141 - INFO - 完成【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-16 19:50:09,330 - INFO - 儲存檔案至路徑：.\output7\【河洛文讀注音-雅俗通】《岳陽樓記》.xlsx
2025-01-16 19:50:09,330 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-16 19:56:27,825 - INFO - 作業開始
2025-01-16 19:56:27,827 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 19:56:27,860 - INFO - 【待注音漢字】總字數為: 448
2025-01-16 19:56:28,035 - INFO - 儲存格內容清除完畢
2025-01-16 19:56:34,187 - INFO - 儲存格格式重設完畢
2025-01-16 19:57:06,332 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-16 19:57:06,369 - INFO - 開始【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-16 19:59:26,091 - INFO - 完成【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-16 19:59:26,317 - INFO - 儲存檔案至路徑：.\output7\【河洛文讀注音-雅俗通】《岳陽樓記》.xlsx
2025-01-16 19:59:26,318 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-16 20:00:32,420 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:01:01,214 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-16 20:01:01,214 - INFO - 完成【處理作業】...
2025-01-16 20:01:01,308 - INFO - 釋放 Excel 資源，處理完成。
2025-01-16 20:01:01,308 - INFO - 作業成功完成！
2025-01-16 20:04:37,053 - INFO - 作業開始
2025-01-16 20:04:37,053 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:04:37,087 - INFO - 【待注音漢字】總字數為: 448
2025-01-16 20:04:37,188 - INFO - 儲存格內容清除完畢
2025-01-16 20:04:43,380 - INFO - 儲存格格式重設完畢
2025-01-16 20:05:16,100 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-16 20:05:16,137 - INFO - 開始【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-16 20:07:36,157 - INFO - 完成【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-16 20:07:36,366 - INFO - 儲存檔案至路徑：.\output7\【河洛文讀注音-雅俗通】《岳陽樓記》.xlsx
2025-01-16 20:07:36,366 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-16 20:07:44,077 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:10:57,379 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:11:58,150 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:16:42,309 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:20:06,196 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:22:00,319 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:23:25,816 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:26:27,624 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:28:51,332 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:31:04,880 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:33:12,914 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:36:43,432 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:39:55,557 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:41:23,712 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:43:08,376 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-16 20:43:08,377 - INFO - 完成【處理作業】...
2025-01-16 20:43:08,457 - INFO - 釋放 Excel 資源，處理完成。
2025-01-16 20:43:08,457 - INFO - 作業成功完成！
2025-01-16 20:44:13,101 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:45:34,342 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:49:07,569 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:50:30,367 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-16 20:50:30,368 - INFO - 完成【處理作業】...
2025-01-16 20:50:30,442 - INFO - 釋放 Excel 資源，處理完成。
2025-01-16 20:50:30,442 - INFO - 作業成功完成！
2025-01-16 20:51:01,499 - INFO - 作業開始
2025-01-16 20:51:01,500 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:51:01,535 - INFO - 【待注音漢字】總字數為: 448
2025-01-16 20:51:01,677 - INFO - 儲存格內容清除完畢
2025-01-16 20:51:08,107 - INFO - 儲存格格式重設完畢
2025-01-16 20:51:40,192 - INFO - 待注音漢字已填入【漢字注音】工作表
2025-01-16 20:51:40,228 - INFO - 開始【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-16 20:53:59,436 - INFO - 完成【漢字標音作業】 - 河洛話: <class 'type'>
2025-01-16 20:53:59,639 - INFO - 儲存檔案至路徑：.\output7\【河洛文讀注音-雅俗通】《岳陽樓記》.xlsx
2025-01-16 20:53:59,639 - INFO - a701_作業中活頁簿填入漢字.py 程式已執行完畢！
2025-01-16 20:55:12,977 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 20:56:15,724 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 21:03:16,557 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 21:12:32,610 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 21:16:36,489 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 21:17:25,355 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 21:19:18,675 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 21:26:35,215 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 21:47:25,513 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 21:49:34,378 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 22:06:26,561 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-16 22:08:21,023 - INFO - 完成【作業程序】：更新漢字標音並同步【標音字庫】內容...
2025-01-16 22:08:21,023 - INFO - 完成【處理作業】...
2025-01-16 22:08:21,128 - INFO - 釋放 Excel 資源，處理完成。
2025-01-16 22:08:21,128 - INFO - 作業成功完成！
2025-01-18 11:44:28,378 - INFO - 作業開始
2025-01-18 11:44:28,380 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-18 11:47:02,586 - INFO - 己存檔至路徑：{file_path}
2025-01-18 11:47:02,586 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-18 11:47:02,586 - INFO - 作業完成！
2025-01-23 11:16:16,839 - INFO - 作業開始
2025-01-23 11:16:16,841 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-23 11:16:16,842 - ERROR - 無法找到作用中的 Excel 工作簿: 'NoneType' object has no attribute 'books'
Traceback (most recent call last):
  File "mod_excel_access.py", line 530, in main
    wb = xw.apps.active.books.active    # 取得 Excel 作用中的活頁簿檔案
         ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'books'
2025-01-23 11:19:12,111 - INFO - 作業開始
2025-01-23 11:19:15,153 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-23 11:20:26,360 - ERROR - 無法找到作用中的 Excel 工作簿: 'NoneType' object has no attribute 'books'
Traceback (most recent call last):
  File "mod_excel_access.py", line 530, in main
    wb = xw.apps.active.books.active    # 取得 Excel 作用中的活頁簿檔案
         ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'books'
2025-01-23 11:22:59,514 - INFO - 作業開始
2025-01-23 11:22:59,516 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-23 11:22:59,541 - ERROR - 作業過程發生未知的異常錯誤: No such file: 'Test_Case_Sample.xlsx'
Traceback (most recent call last):
  File "mod_excel_access.py", line 544, in main
    result_code = process(wb)
  File "mod_excel_access.py", line 478, in process
    return_code = ut_khuat_ji_piau(wb=wb)
  File "mod_excel_access.py", line 346, in ut_khuat_ji_piau
    wb = xw.Book('Test_Case_Sample.xlsx')
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 933, in __init__
    impl = app.books.open(
           ~~~~~~~~~~~~~~^
        fullname,
        ^^^^^^^^^
    ...<13 lines>...
        corrupt_load,
        ^^^^^^^^^^^^^
    ).impl
    ^
  File "c:\work\Piau-Im\.venv\Lib\site-packages\xlwings\main.py", line 5157, in open
    raise FileNotFoundError("No such file: '%s'" % fullname)
FileNotFoundError: No such file: 'Test_Case_Sample.xlsx'
2025-01-23 13:35:51,118 - INFO - 作業開始
2025-01-23 13:35:51,119 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-23 13:46:27,529 - INFO - 作業開始
2025-01-23 13:46:27,530 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-23 13:52:24,984 - INFO - 作業開始
2025-01-23 13:52:24,985 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-23 13:59:10,848 - INFO - 作業開始
2025-01-23 13:59:10,849 - INFO - 專案根目錄為: C:\work\Piau-Im
2025-01-23 14:02:32,100 - INFO - 己存檔至路徑：{file_path}
2025-01-23 14:02:32,100 - INFO - a702_查找及填入漢字標音.py 程式已執行完畢！
2025-01-23 14:02:32,100 - INFO - 作業完成！
